# Web Scraping - Internetten veri kazima

In [ ]:
#pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/zaid/Desktop/Yapay-Zeka-Kursu/venv/lib/python3.14/site-packages (from beautifulsoup4) (4.15.0)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [beautifulsoup4]
Successfully installed beautifulsoup4-4.14.3 soupsieve-2.8.4
Note: you may need to restart the kernel to use updated packages.

In [3]:
from bs4 import BeautifulSoup as soup

In [4]:
import requests

In [6]:
page=requests.get('http://localhost:8080/')

In [15]:
page.content

b'<html>\r\n<head>\r\n<meta charset="utf-8">\r\n<title> Benim duygusal web sayfam </title>\r\n\r\n</head>\r\n\r\n<body bgcolor="#EDA421">\r\n<audio autoplay loop hidden>\r\n<source src=\'uzulme.mp3\' type=audio/mpeg>\r\n</audio>\r\n<center>\r\n<marquee direction=left> <h1> <font color=red>G\xc3\xb6nl\xc3\xbcmde mevsim hep sonbahar</font> </h1></marquee>\r\n<marquee direction=right><h3><font color=green>Ve bir ak\xc5\x9fam\xc3\xbcst\xc3\xbc yan\xc4\xb1n\xc4\xb1zda kimseler olmaz</font></h3></marquee>\r\n\r\n<img src=\'https://images.pexels.com/photos/33109/fall-autumn-red-season.jpg\' width=800>\r\n\r\n<table border=1 width=75%>\r\n<tr>\r\n<td>\r\n<h3> G\xc3\xb6nl\xc3\xbcmde Mevsim Hep Sonbahar</h3>\r\n<p>\r\nG\xc3\xb6nl\xc3\xbcmde mevsim hep sonbahar,<br>\r\nDallar k\xc4\xb1r\xc4\xb1k, r\xc3\xbczg\xc3\xa2r yorgun.<br>\r\nBir eski \xc5\x9fark\xc4\xb1 \xc3\xa7alar uzaktan,<br>\r\nAd\xc4\xb1n\xc4\xb1 f\xc4\xb1s\xc4\xb1ldar yapraklar.<br><br>\r\n\r\nSokaklar sessiz, dostlar uzak,<br>\r\nCamlarda yaln\xc4\xb1zl\xc4\xb1k bu\xc4\x9fusu.<br>\r\nBir kahve kokusu kalm\xc4\xb1\xc5\x9f senden,<br>\r\nBir de unutulmu\xc5\x9f bir g\xc3\xbcl\xc3\xbc\xc5\x9f.<br><br>\r\n\r\nNe bahar gelir, ne yaz u\xc4\x9frar,<br>\r\nKalbim sararm\xc4\xb1\xc5\x9f bir defter gibi.<br>\r\nSayfalar\xc4\xb1nda sen vars\xc4\xb1n h\xc3\xa2l\xc3\xa2,<br>\r\nSilinmeyen bir iz gibi.<br><br>\r\n\r\nBilirim, d\xc3\xb6nmez art\xc4\xb1k o g\xc3\xbcnler,<br>\r\nAma beklerim yine, inatla.<br>\r\n\xc3\x87\xc3\xbcnk\xc3\xbc g\xc3\xb6nl\xc3\xbcmde mevsim hep sonbahar,<br>\r\nVe sen \xe2\x80\x94 hep oradas\xc4\xb1n, yapraklarda\xe2\x80\xa6\r\n\r\n</p>\r\n</td><td><h3>Dost</h3>\r\n<p>\r\nBir gece habersiz bize gel<br>\r\nMerdivenler g\xc4\xb1c\xc4\xb1rdamas\xc4\xb1n<br>\r\n\xc3\x96yle yorgunum ki hi\xc3\xa7 sorma<br>\r\nSen halimden anlars\xc4\xb1n<br>\r\nSabahlara kadar oturup konu\xc5\x9fal\xc4\xb1m<br>\r\nKimse duymas\xc4\xb1n<br>\r\nMavi bir g\xc3\xb6ky\xc3\xbcz\xc3\xbcm\xc3\xbcz olsun kanatlar\xc4\xb1m\xc4\xb1z<br>\r\nDokunarak u\xc3\xa7al\xc4\xb1m.<br><br>\r\n\r\ninsanlardan buz gibi so\xc4\x9fudum,<br>\r\ni\xc5\x9fte yaln\xc4\xb1z sen vars\xc4\xb1n<br>\r\n\xc3\x96yle halsizim ki hi\xc3\xa7 sorma<br>\r\nAnlars\xc4\xb1n.\r\n</p>\r\n\r\n</td>\r\n</tr>\r\n<tr>\r\n<td>\r\n<h3> Sessiz Gemi</h3>\r\n<p>\r\n\r\n<pre>\r\nArt\xc4\xb1k demir almak g\xc3\xbcn\xc3\xbc gelmi\xc5\x9fse zamandan\r\nMe\xc3\xa7hule giden bir gemi kalkar bu limandan.\r\n\r\nHi\xc3\xa7 yolcusu yokmu\xc5\x9f gibi sessizce al\xc4\xb1r yol;\r\nSallanmaz o kalk\xc4\xb1\xc5\x9fta ne mendil, ne de bir kol.\r\n\r\nR\xc4\xb1ht\xc4\xb1mda kalanlar bu seyahatten elemli,\r\nG\xc3\xbcnlerce siyah ufka bakar g\xc3\xb6zleri nemli,\r\n\r\nBi\xc3\xa7are g\xc3\xb6n\xc3\xbcller! Ne giden son gemidir bu!\r\nHicranl\xc4\xb1 hayat\xc4\xb1n ne de son matemidir bu.\r\n\r\nD\xc3\xbcnyada sevilmi\xc5\x9f ve seven nafile bekler;\r\nBilmez ki giden sevgililer d\xc3\xb6nmeyecekler.\r\n\r\nBir \xc3\xa7ok gidenin her biri memnun ki yerinden,\r\nBir \xc3\xa7ok seneler ge\xc3\xa7ti; d\xc3\xb6nen yok seferinden.\r\n</pre>\r\n</p>\r\n</td><td><h3>Hikaye</h3>\r\n<p>\r\n<pre>\r\nSenin dudaklar\xc4\xb1n pembe\r\nEllerin beyaz,\r\nAl tut ellerimi bebek\r\nTut biraz!\r\n\r\nBenim do\xc4\x9fdu\xc4\x9fum k\xc3\xb6ylerde\r\nCeviz a\xc4\x9fa\xc3\xa7lar\xc4\xb1 yoktu,\r\nBen bu y\xc3\xbczden serinli\xc4\x9fe hasretim\r\nOk\xc5\x9fa biraz!\r\n\r\nBenim do\xc4\x9fdu\xc4\x9fum k\xc3\xb6ylerde\r\nBu\xc4\x9fday tarlalar\xc4\xb1 yoktu,\r\nDa\xc4\x9f\xc4\xb1t sa\xc3\xa7lar\xc4\xb1n\xc4\xb1 bebek\r\nSavur biraz!\r\n\r\nBenim do\xc4\x9fdu\xc4\x9fum k\xc3\xb6yleri\r\nAk\xc5\x9famlar\xc4\xb1 e\xc5\x9fkiyalar basard\xc4\xb1.\r\nBen bu y\xc3\xbczden yaln\xc4\xb1zl\xc4\xb1\xc4\x9f\xc4\xb1 hi\xc3\xa7 sevmem\r\nKonu\xc5\x9f biraz!\r\n\r\nBenim do\xc4\x9fdu\xc4\x9fum k\xc3\xb6ylerde\r\n\xc5\x9eimal r\xc3\xbczgarlar\xc4\xb1 eserdi,\r\nVe bu y\xc3\xbczden dudaklar\xc4\xb1m \xc3\xa7atlakt\xc4\xb1r\r\n\xc3\x96p biraz!\r\n\r\nSen T\xc3\xbcrkiye gibi ayd\xc4\xb1nl\xc4\xb1k ve g\xc3\xbczelsin!\r\nBenim do\xc4\x9fdu\xc4\x9fum k\xc3\xb6yler de g\xc3\xbczeldi,\r\nSen de anlat do\xc4\x9fdu\xc4\x9fun yerleri,\r\nAnlat biraz!\r\n</pre>\r\n</p>\r\n\r\n</td>\r\n</tr>\r\n</table>\r\n<form name=form1 action=post>\r\nIsim: <input type=text name=isim><br>\r\nEmail: <input type=text name=email><br>\r\n<input type=submit value=\'Gonder\'>\r\n</center>\r\n\r\n</body>\r\n</html>'

In [16]:
sp=soup(page.content, 'html.parser')

In [17]:
sp2=sp.prettify

In [10]:
sp2

<bound method Tag.prettify of <html>
<head>
<meta charset="utf-8"/>
<title> Benim duygusal web sayfam </title>
</head>
<body bgcolor="#EDA421">
<audio autoplay="" hidden="" loop="">
<source src="uzulme.mp3" type="audio/mpeg"/>
</audio>
<center>
<marquee direction="left"> <h1> <font color="red">Gönlümde mevsim hep sonbahar</font> </h1></marquee>
<marquee direction="right"><h3><font color="green">Ve bir akşamüstü yanınızda kimseler olmaz</font></h3></marquee>
<img src="https://images.pexels.com/photos/33109/fall-autumn-red-season.jpg" width="800"/>
<table border="1" width="75%">
<tr>
<td>
<h3> Gönlümde Mevsim Hep Sonbahar</h3>
<p>
Gönlümde mevsim hep sonbahar,<br/>
Dallar kırık, rüzgâr yorgun.<br/>
Bir eski şarkı çalar uzaktan,<br/>
Adını fısıldar yapraklar.<br/><br/>

Sokaklar sessiz, dostlar uzak,<br/>
Camlarda yalnızlık buğusu.<br/>
Bir kahve kokusu kalmış senden,<br/>
Bir de unutulmuş bir gülüş.<br/><br/>

Ne bahar gelir, ne yaz uğrar,<br/>
Kalbim sararmış bir defter gibi.<br/>
Sayfalarında sen varsın hâlâ,<br/>
Silinmeyen bir iz gibi.<br/><br/>

Bilirim, dönmez artık o günler,<br/>
Ama beklerim yine, inatla.<br/>
Çünkü gönlümde mevsim hep sonbahar,<br/>
Ve sen — hep oradasın, yapraklarda…

</p>
</td><td><h3>Dost</h3>
<p>
Bir gece habersiz bize gel<br/>
Merdivenler gıcırdamasın<br/>
Öyle yorgunum ki hiç sorma<br/>
Sen halimden anlarsın<br/>
Sabahlara kadar oturup konuşalım<br/>
Kimse duymasın<br/>
Mavi bir gökyüzümüz olsun kanatlarımız<br/>
Dokunarak uçalım.<br/><br/>

insanlardan buz gibi soğudum,<br/>
işte yalnız sen varsın<br/>
Öyle halsizim ki hiç sorma<br/>
Anlarsın.
</p>
</td>
</tr>
<tr>
<td>
<h3> Sessiz Gemi</h3>
<p>
<pre>
Artık demir almak günü gelmişse zamandan
Meçhule giden bir gemi kalkar bu limandan.

Hiç yolcusu yokmuş gibi sessizce alır yol;
Sallanmaz o kalkışta ne mendil, ne de bir kol.

Rıhtımda kalanlar bu seyahatten elemli,
Günlerce siyah ufka bakar gözleri nemli,

Biçare gönüller! Ne giden son gemidir bu!
Hicranlı hayatın ne de son matemidir bu.

Dünyada sevilmiş ve seven nafile bekler;
Bilmez ki giden sevgililer dönmeyecekler.

Bir çok gidenin her biri memnun ki yerinden,
Bir çok seneler geçti; dönen yok seferinden.
</pre>
</p>
</td><td><h3>Hikaye</h3>
<p>
<pre>
Senin dudakların pembe
Ellerin beyaz,
Al tut ellerimi bebek
Tut biraz!

Benim doğduğum köylerde
Ceviz ağaçları yoktu,
Ben bu yüzden serinliğe hasretim
Okşa biraz!

Benim doğduğum köylerde
Buğday tarlaları yoktu,
Dağıt saçlarını bebek
Savur biraz!

Benim doğduğum köyleri
Akşamları eşkiyalar basardı.
Ben bu yüzden yalnızlığı hiç sevmem
Konuş biraz!

Benim doğduğum köylerde
Şimal rüzgarları eserdi,
Ve bu yüzden dudaklarım çatlaktır
Öp biraz!

Sen Türkiye gibi aydınlık ve güzelsin!
Benim doğduğum köyler de güzeldi,
Sen de anlat doğduğun yerleri,
Anlat biraz!
</pre>
</p>
</td>
</tr>
</table>
<form action="post" name="form1">
Isim: <input name="isim" type="text"/><br/>
Email: <input name="email" type="text"/><br/>
<input type="submit" value="Gonder"/>
</form></center>
</body>
</html>>

In [18]:
siir=sp.find_all('p')

In [19]:
siir

[<p>
 Gönlümde mevsim hep sonbahar,<br/>
 Dallar kırık, rüzgâr yorgun.<br/>
 Bir eski şarkı çalar uzaktan,<br/>
 Adını fısıldar yapraklar.<br/><br/>

 Sokaklar sessiz, dostlar uzak,<br/>
 Camlarda yalnızlık buğusu.<br/>
 Bir kahve kokusu kalmış senden,<br/>
 Bir de unutulmuş bir gülüş.<br/><br/>

 Ne bahar gelir, ne yaz uğrar,<br/>
 Kalbim sararmış bir defter gibi.<br/>
 Sayfalarında sen varsın hâlâ,<br/>
 Silinmeyen bir iz gibi.<br/><br/>

 Bilirim, dönmez artık o günler,<br/>
 Ama beklerim yine, inatla.<br/>
 Çünkü gönlümde mevsim hep sonbahar,<br/>
 Ve sen — hep oradasın, yapraklarda…

 </p>,
 <p>
 Bir gece habersiz bize gel<br/>
 Merdivenler gıcırdamasın<br/>
 Öyle yorgunum ki hiç sorma<br/>
 Sen halimden anlarsın<br/>
 Sabahlara kadar oturup konuşalım<br/>
 Kimse duymasın<br/>
 Mavi bir gökyüzümüz olsun kanatlarımız<br/>
 Dokunarak uçalım.<br/><br/>

 insanlardan buz gibi soğudum,<br/>
 işte yalnız sen varsın<br/>
 Öyle halsizim ki hiç sorma<br/>
 Anlarsın.
 </p>,
 <p>
 <pre>
 Artık demir almak günü gelmişse zamandan
 Meçhule giden bir gemi kalkar bu limandan.

 Hiç yolcusu yokmuş gibi sessizce alır yol;
 Sallanmaz o kalkışta ne mendil, ne de bir kol.

 Rıhtımda kalanlar bu seyahatten elemli,
 Günlerce siyah ufka bakar gözleri nemli,

 Biçare gönüller! Ne giden son gemidir bu!
 Hicranlı hayatın ne de son matemidir bu.

 Dünyada sevilmiş ve seven nafile bekler;
 Bilmez ki giden sevgililer dönmeyecekler.

 Bir çok gidenin her biri memnun ki yerinden,
 Bir çok seneler geçti; dönen yok seferinden.
 </pre>
 </p>,
 <p>
 <pre>
 Senin dudakların pembe
 Ellerin beyaz,
 Al tut ellerimi bebek
 Tut biraz!

 Benim doğduğum köylerde
 Ceviz ağaçları yoktu,
 Ben bu yüzden serinliğe hasretim
 Okşa biraz!

 Benim doğduğum köylerde
 Buğday tarlaları yoktu,
 Dağıt saçlarını bebek
 Savur biraz!

 Benim doğduğum köyleri
 Akşamları eşkiyalar basardı.
 Ben bu yüzden yalnızlığı hiç sevmem
 Konuş biraz!

 Benim doğduğum köylerde
 Şimal rüzgarları eserdi,
 Ve bu yüzden dudaklarım çatlaktır
 Öp biraz!

 Sen Türkiye gibi aydınlık ve güzelsin!
 Benim doğduğum köyler de güzeldi,
 Sen de anlat doğduğun yerleri,
 Anlat biraz!
 </pre>
 </p>]

In [12]:
siir[3]

<p>
<pre>
Senin dudakların pembe
Ellerin beyaz,
Al tut ellerimi bebek
Tut biraz!

Benim doğduğum köylerde
Ceviz ağaçları yoktu,
Ben bu yüzden serinliğe hasretim
Okşa biraz!

Benim doğduğum köylerde
Buğday tarlaları yoktu,
Dağıt saçlarını bebek
Savur biraz!

Benim doğduğum köyleri
Akşamları eşkiyalar basardı.
Ben bu yüzden yalnızlığı hiç sevmem
Konuş biraz!

Benim doğduğum köylerde
Şimal rüzgarları eserdi,
Ve bu yüzden dudaklarım çatlaktır
Öp biraz!

Sen Türkiye gibi aydınlık ve güzelsin!
Benim doğduğum köyler de güzeldi,
Sen de anlat doğduğun yerleri,
Anlat biraz!
</pre>
</p>

In [20]:
siir[3].text.replace('<br>',' ').replace('\r',' ').replace('\n',' ')

'   Senin dudakların pembe  Ellerin beyaz,  Al tut ellerimi bebek  Tut biraz!    Benim doğduğum köylerde  Ceviz ağaçları yoktu,  Ben bu yüzden serinliğe hasretim  Okşa biraz!    Benim doğduğum köylerde  Buğday tarlaları yoktu,  Dağıt saçlarını bebek  Savur biraz!    Benim doğduğum köyleri  Akşamları eşkiyalar basardı.  Ben bu yüzden yalnızlığı hiç sevmem  Konuş biraz!    Benim doğduğum köylerde  Şimal rüzgarları eserdi,  Ve bu yüzden dudaklarım çatlaktır  Öp biraz!    Sen Türkiye gibi aydınlık ve güzelsin!  Benim doğduğum köyler de güzeldi,  Sen de anlat doğduğun yerleri,  Anlat biraz!   '

In [21]:
page=requests.get('https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320')

In [22]:
sp=soup(page.content, 'html.parser')

In [23]:
sp

<!DOCTYPE html>

<html lang="tr">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Herkes nerede? - Zafer Acar</title>
<meta content="Los Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine..." name="description"/>
<link href="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" rel="canonical"/>
<meta content="article" property="og:type"/>
<meta content="KARAR" property="og:site_name"/>
<meta content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" property="og:url"/>
<meta content="Herkes nerede? - Zafer Acar" property="og:title"/>
<meta content="Los Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine..." property="og:description"/>
<meta content="https://cdn.karar.com/author/zafer-acar-002.jpg" property="og:image"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@KararHaber" name="twitter:site"/>
<meta content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" name="twitter:url"/>
<meta content="Herkes nerede? - Zafer Acar" name="twitter:title"/>
<meta content="Los Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine..." name="twitter:description"/>
<meta content="https://cdn.karar.com/author/zafer-acar-002.jpg" name="twitter:image"/>
<meta content="Zafer Acar" name="author"/>
<meta content="Herkes nerede?" name="title"/>
<meta content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" name="url"/>
<meta content="2018-06-24T23:23:46+03:00" name="datePublished"/>
<meta content="columnist" name="articleSection"/>
<meta content="Zafer Acar" name="articleAuthor"/>
<meta content="app-id=1009271502" name="apple-itunes-app"/>
<meta content="app-id=com.labdroids.karar" name="google-play-app"/>
<meta content="668763830688221" property="fb:app_id"/>
<link href="https://www.karar.com/service/rss.php" rel="alternate" type="application/rss+xml"/>
<meta content="max-snippet:-1, max-image-preview:large, max-video-preview:-1" name="robots"/>
<link href="/manifest.json" rel="manifest"/>
<link href="https://www.karar.com/d/assets/favicon/favicon.ico" rel="icon"/>
<meta content="CM News 6.0" name="generator"/>
<link href="https://www.karar.com/d/assets/bundle/karar-desktop-main.css?1771472334" rel="stylesheet"/>
<script>
			const BURL = "https://www.karar.com/",
				DURL = "https://cdn.karar.com/";
					</script>
<link href="https://cdn.karar.com/assets/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link color="#e30613" href="https://cdn.karar.com/assets/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<meta content="#e30613" name="msapplication-TileColor"/>
<meta content="#ffffff" name="theme-color"/>
<meta content="fd13614ab1" name="Petal-Search-site-verification">
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1L3TVQZ3LV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-1L3TVQZ3LV');
</script>
<script>!function(){var t=document.createElement("script");t.setAttribute("src",'https://cdn.p.analitik.bik.gov.tr/tracker'+(typeof Intl!=="undefined"?(typeof (Intl||"").PluralRules!=="undefined"?'1':typeof Promise!=="undefined"?'2':typeof MutationObserver!=='undefined'?'3':'4'):'4')+'.js'),t.setAttribute("data-website-id","d9b8fdca-5069-4cc2-b3f3-6ab32564a106"),t.setAttribute("data-host-url",'//d9b8fdca-5069-4cc2-b3f3-6ab32564a106.collector.p.analitik.bik.gov.tr'),document.head.appendChild(t)}();</script>
<!-- Google Tag Manager / Karar GTM -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KXB9WDF9');</script>
<!-- End Google Tag Manager --> <!--<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5668552793696977" crossorigin="anonymous"></script>-->
<script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
<script async="" src="https://cdn.adsby.io/headerbidding/adshb.prebid.js"></script>
<script async="" src="https://cdn.adsby.io/karar/theadsiov2.js"></script>
<script>

    window.googletag = window.googletag || { cmd: [] };


	googletag.cmd.push(function ()
	{
		mappingFull = googletag.sizeMapping().
		addSize([1024, 360], [[970, 90], [1000, 250], [970, 250]]).
		addSize([768, 360], [[728, 250], [728, 90]]).
		addSize([360, 360], [[336, 280], [300, 250]]).
		addSize([0, 0], [[320, 100],[300, 100]]).
		build();

		mappingMiddle = googletag.sizeMapping().
		addSize([768, 360], [[670, 250], [640, 300], [336, 280], [300, 250], 'fluid']).
		addSize([360, 360], [[336, 280], [300, 250]]).
		addSize([0, 0], [300, 250]).
		build();

		mappingSide = googletag.sizeMapping().
		addSize([360, 360], [[336, 280], [300, 250], 'fluid']).
		addSize([0, 0], [300, 250]).
		build();

		mappingSticky = googletag.sizeMapping().
		addSize([1024, 360], [970, 90]).
		addSize([768, 360], [728, 90]).
		addSize([0, 0], [[300, 100],[320,100]]).
		build();

		mappingPageSkin = googletag.sizeMapping().
		addSize([1720, 600], [[300, 600],[160, 600],[120, 600]]).
		addSize([1520, 600], [[160, 600],[120, 600]]).
		addSize([1440, 600], [[160, 600],[120, 600]]).
		addSize([1366, 600], [[120, 600]]).
		addSize([0, 0], []).
		build();

		mappingMobilM = googletag.sizeMapping().
		addSize([0, 0], [[300, 50], [320, 100], [320, 50], [300, 100]]).
		build();
		mappingMobilSC = googletag.sizeMapping().
		addSize([0, 0], [[300,250], [336, 280]]).
		build();

        googletag.setConfig({ disableInitialLoad: true });
        googletag.setConfig({ singleRequest: true });
		googletag.enableServices();
	});



</script>
<script async="" src="https://jsc.idealmedia.io/site/839414.js"></script>
<style>
    .article-detail .google-auto-placed{
        margin-bottom: 30px;
    }
</style> </meta></head>
<body class="body-main cat-author author-article-detail author">
<header class="main-header">
<div class="top">
<div class="container">
<div class="date">07 Haziran 2026 Pazar</div>
<div class="currency">
<div class="item down">
<span class="text">Altın</span>
<i class="icon icon-down-dir"></i>
<span class="value">6408.33</span>
<span class="rate">%0</span>
</div>
<div class="item down">
<span class="text">BIST</span>
<i class="icon icon-down-dir"></i>
<span class="value">13694.19</span>
<span class="rate">%0</span>
</div>
<div class="item down">
<span class="text">Dolar</span>
<i class="icon icon-down-dir"></i>
<span class="value">45.9704</span>
<span class="rate">%0</span>
</div>
<div class="item down">
<span class="text">Euro</span>
<i class="icon icon-down-dir"></i>
<span class="value">53.01</span>
<span class="rate">%0</span>
</div>
</div>
<div class="social">
<a class="youtube" href="https://www.youtube.com/channel/UCoLyFzOzAzNG_-oR-O4relg?sub_confirmation=1" rel="nofollow noopener noreferrer" target="_blank" title="Youtube ile takip et"><i class="icon icon-youtube-play"></i></a>
<a class="instagram" href="https://www.instagram.com/kararhaber" rel="nofollow noopener noreferrer" target="_blank" title="İnstagram ile takip et"><i class="icon icon-instagramm"></i></a>
<a class="facebook" href="https://www.facebook.com/KararHaber" rel="nofollow noopener noreferrer" target="_blank" title="Facebook ile takip et"><i class="icon icon-facebook"></i></a>
<a class="twitter" href="https://twitter.com/KararHaber" rel="nofollow noopener noreferrer" target="_blank" title="Twitter ile takip et"><i class="icon icon-twitter"></i></a>
</div>
</div>
</div>
<div class="center">
<div class="container">
<div class="logo relative">
<a href="https://www.karar.com/" rel="home" title="KARAR">
<img alt="KARAR" class="lazy" height="60" loading="lazy" src="https://www.karar.com/d/assets/logo-white.svg" width="233"/>
</a>
</div>
<div class="flex middle">
<form action="/ara" method="get">
<div class="search-wrapper flex middle">
<input class="search-input" name="key" placeholder="Aranacak kelime" type="text"/>
<i class="icon icon-search"></i>
</div>
</form>
<div class="weather flex middle">
<i class="icon icon-accu-1"></i>
<span class="value">28°</span>
<div class="parameter margin-left-md">
<div class="city">İstanbul</div>
<div>Güneşli</div>
</div>
</div>
</div>
</div>
</div>
<div class="main-nav">
<div class="container">
<ul class="flex middle">
<li>
<a alt="Anasayfa" href="/"><i class="icon-home"></i> </a>
</li>
<li>
<a alt="Güncel" href="/guncel-haberler">Güncel</a>
</li>
<li>
<a alt="Yazarlar" href="/yazarlar">Yazarlar</a>
</li>
<li>
<a alt="Dünya" href="/dunya-haberleri">Dünya</a>
</li>
<li>
<a alt="Ekonomi" href="/ekonomi-haberleri">Ekonomi</a>
</li>
<li>
<a alt="Spor" href="/spor-haberleri">Spor</a>
</li>
<li>
<a alt="Hayat" href="/hayat-haberleri">Hayat</a>
</li>
<li>
<a alt="Karar Video" href="/karar-tv">Karar Video</a>
</li>
<li>
<a alt="Görüşler" href="/gorusler">Görüşler</a>
</li>
<li>
<a alt="Resmi İlanlar" href="/resmi-ilanlar">Resmi İlanlar</a>
</li>
<li>
<a alt="Kültür Sanat" href="/kultur-sanat-haberleri">Kültür Sanat</a>
</li>
<li>
<a aria-label="Menu" class="menu show-all-menu" href="#"><i class="icon-menu"></i></a>
</li>
</ul>
</div>
</div>
</header>
<div class="last-news">
<div class="container flex middle">
<div class="block-title"><a href="/son-dakika">SON DAKİKA :</a>
</div>
<div class="news-content">
<div class="swiper-container">
<div class="swiper-wrapper">
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/otokoc-genel-mudurlugune-silahli-saldiri-genel-baskan-inan-ekici-mi-2052317">Otokoç Genel Müdürlüğü'ne silahlı saldırı: Genel Başkan İnan Ekici mi hedef, Rahmi Koç mu?</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/can-polat-cinayetinde-4-supheli-adliyeye-sevk-edildi-2052315">Can Polat cinayetinde 4 şüpheli adliyeye sevk edildi</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/avcilarda-korkutan-olay-3-katli-binanin-kolonu-yan-binanin-odasina-dustu-2052314">Avcılar'da korkutan olay! 3 katlı binanın kolonu yan binanın odasına düştü</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/akom-acikladi-istanbulda-yeni-haftada-yagis-beklenmiyor-2052313">AKOM açıkladı: İstanbul'da yeni haftada yağış beklenmiyor</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/pendikte-yol-verme-kavgasi-kaputu-acip-aracim-ariza-yapti-dedi-polisi-2052309">Pendik’te yol verme kavgası: Kaputu açıp 'aracım arıza yaptı' dedi, polisi arayınca ikna oldu</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/iki-uzman-isimden-sicaklik-ve-orman-yangini-uyarisi-daha-once-2052308">İki uzman isimden 'sıcaklık' ve 'orman yangını' uyarısı: Daha önce görülmemiş sıcaklıklar yaşanabilir</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/bakanlik-duyurdu-unlu-kuruyemis-urunlerinde-kanserojen-madde-tespit-2052306">Bakanlık duyurdu: Ünlü kuruyemiş ürünlerinde kanserojen madde tespit edildi</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/kayip-olarak-aranan-kucuk-kizdan-aci-haber-5-yasindaki-menesa-bahcedeki-2052305">Kayıp olarak aranan küçük kızdan acı haber! 5 yaşındaki Menesa bahçedeki havuzda ölü bulundu</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/2026-e-okul-ne-zaman-kapanacak-vbs-e-okul-not-girisi-ne-zaman-bitecek-2052304">2026 e-Okul ne zaman kapanacak? VBS e-Okul not girişi ne zaman bitecek?</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/chp-sozcusu-muslim-sari-bir-tepki-var-ama-muthis-bir-kopurtme-de-var-2052300">CHP Sözcüsü Müslim Sarı: Bir tepki var ama müthiş bir köpürtme de var</a>
</div>
</div>
</div>
</div>
</div>
</div>
<section class="breadcrumbs">
<div class="container">
<ol>
<li><a href="https://www.karar.com/"><span><i class="icon-home"></i> Anasayfa</span></a></li>
<li><a href="https://www.karar.com/yazarlar"><span>Yazarlar</span></a></li>
<li><a href="https://www.karar.com/yazarlar/zafer-acar"><span>Zafer Acar</span></a></li>
<li><span>Herkes nerede?</span></li>
</ol>
</div>
</section> <main role="main">
<div class="banner-pageskin container"><div class="pageskin-left"><div class="fixed"><the-ads data-adunit="/karar.com/karar_desktop_pageskin_L" data-device="desktop" data-sizes="[[120, 240], [120, 600]]"></the-ads></div></div><div class="pageskin-right"><div class="fixed"><the-ads data-adunit="/karar.com/karar_desktop_pageskin_R" data-device="desktop" data-sizes="[[160, 600], [120, 240], [120, 600]]"></the-ads></div></div></div> <div class="container section-padding-gutter">
<section class="banner banner-wide"><the-ads data-adunit="/karar.com/karar_desktop_masthead" data-device="desktop" data-sizes="[[728, 90], [970, 250], [970, 90], [1000, 250], 'fluid']" style="
    display:block;
height:250px;
overflow: hidden;
position: relative;
"></the-ads></section>
<div class="page-content author-page">
<div class="author-info box-shadow">
<header class="w-100">
<a href="/yazarlar">Bugünkü Yazarlar</a>
<a href="/yazarlar#tumu">Tüm Yazarlar</a>
</header>
<div class="image r1x1">
<img alt="Zafer Acar" src="https://cdn.karar.com/author/75_b.jpg"/>
</div>
<div class="info">
<h1 class="name">Zafer Acar</h1>
<div class="mb-2"><span data-erot="mnsrenpne@xnene.pbz"></span></div>
<a class="other" href="/yazarlar/zafer-acar" rel="author"><span>Yazarın Tüm Yazıları &gt;</span></a>
</div>
<div class="author-social social">
<a href="https://www.facebook.com/KararHaber " rel="nofollow noopener" target="_blank"><i class="icon-facebook"></i></a>
<a href="https://twitter.com/zaferNasa" rel="nofollow noopener" target="_blank"><i class="icon-twitter"></i></a>
<a href="https://www.instagram.com/kararhaber" rel="nofollow noopener" target="_blank"><i class="icon-instagramm"></i></a>
</div>
</div>
<script>
	document.addEventListener("cmready", function()
	{
		$('[data-erot]').each(function()
		{
			let elm = $(this);
			$(this).replaceWith('<a href="mailto:' + elm.attr('data-erot').replace(/[a-zA-Z]/g, function(c)
			{
				return String.fromCharCode((c <= "Z" ? 90 : 122) >= (c = c.charCodeAt(0) + 13) ? c : c - 26);
			}) + '"><i class="icon-mail"></i></a>')
		})
	});
</script>
<div class="row">
<div class="col-8">
<div class="article-detail author-article-detail">
<div class="content-date">
<time datetime="2018-06-24 23:23:46">24/06/2018 23:23</time>
</div>
<div class="content-heading">
<h1 class="content-title">Herkes nerede?</h1>
</div>
<div class="content-tools flex center between mb-4">
<div class="bookmark-block" data-type="99"></div>
<div class="flex">
<div class="text-size mr-4">
<span class="icon-plus" onclick="changeTextSize('.article-content .text-content', 'u');" role="button" title="Yazıyı büyüt"></span>
<span class="icon-fontsize"></span>
<span class="icon-minus" onclick="changeTextSize('.article-content .text-content', 'd');" role="button" title="Yazıyı küçült"></span>
</div>
<div class="share-block-99">
<span class="icon-print" onclick="window.print();" role="button" title="Yazdır"></span>
<span class="icon-comment-2 comment" onclick="$.scrollTo('#comment_form_7320', 600);" role="button" title="Yorum Yap">
<sup>3</sup>
</span>
</div>
</div>
</div>
<article class="article-content">
<div class="text-content">
<p class="p1"><span class="s1">Los Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine en yakın şehir ise 56 km uzaklıktaki Santa Fe. Los Alamos’ta hayatını devam ettirenler alışveriş ve eğlence için Santa Fe’ye gidip geliyorlar. Yıllar önce yolum Santa Fe’ye düşmüştü. Hazır buraya kadar gelmişken şu Los Alamos’u bir ziyaret edelim dedik. Fakat Santa Fe ziyaretim kızılderililerin yaz festivaline denk gelmişti ve otellerde yer yoktu. Geceyi Santa Fe’nin güneyindeki Albuquerque şehrinde geçirince Los Alamos’a gitmek kısmet olmadı.</span></p><p class="p2"><span class="s1">Peki Los Alamos kasabası bize neyi hatırlatıyor? Tabiki Atom bombasını. İlk atom bombasının yapımı ve test edilmesi ve II. Dünya Savaşı’nın bilimle sonlandırılması tam da bu kasabada bulunan Los Alamos Ulusal Laboratuvar’ında planlanıyor. Hal böyle olunca bu minik kasaba 1940’lardan günümüze kadar hep bilim insanlarını misafir etmiş ve uzun yıllar çoğu Nobel Ödülü sahibi binlerce bilim insanı burada yaşamışlar.</span></p><div class="banner banner-wide"><the-ads data-adunit="/karar.com/karar_desktop_inarticle_middle1" data-device="desktop" data-sizes="[[480, 320], [300, 250], [250, 250], [500, 250], [336, 280], 'fluid']"></the-ads>
<!--<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5668552793696977"
     crossorigin="anonymous"></script>
<ins class="adsbygoogle"
     style="display:block; text-align:center;"
     data-ad-layout="in-article"
     data-ad-format="fluid"
     data-ad-client="ca-pub-5668552793696977"
     data-ad-slot="6380903800"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});

In [28]:
sp.select('article.article-content')[0].text

'\n\nLos Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine en yakın şehir ise 56 km uzaklıktaki Santa Fe. Los Alamos’ta hayatını devam ettirenler alışveriş ve eğlence için Santa Fe’ye gidip geliyorlar. Yıllar önce yolum Santa Fe’ye düşmüştü. Hazır buraya kadar gelmişken şu Los Alamos’u bir ziyaret edelim dedik. Fakat Santa Fe ziyaretim kızılderililerin yaz festivaline denk gelmişti ve otellerde yer yoktu. Geceyi Santa Fe’nin güneyindeki Albuquerque şehrinde geçirince Los Alamos’a gitmek kısmet olmadı.Peki Los Alamos kasabası bize neyi hatırlatıyor? Tabiki Atom bombasını. İlk atom bombasının yapımı ve test edilmesi ve II. Dünya Savaşı’nın bilimle sonlandırılması tam da bu kasabada bulunan Los Alamos Ulusal Laboratuvar’ında planlanıyor. Hal böyle olunca bu minik kasaba 1940’lardan günümüze kadar hep bilim insanlarını misafir etmiş ve uzun yıllar çoğu Nobel Ödülü sahibi binlerce bilim insanı burada yaşamışlar.\n***Los Alamos’ta yaşayan bu bilim insanlarının en önemlilerinden birisi de İtalyan bilim adamı Enrico Fermi idi. Enrico Fermi 1901 yılında Roma’da doğdu. Annesi ilkokul öğretmeni, babası ise demiryolları bakanlığında çalışıyordu. Atom bombasının babası olarak bilinen Fermi fizik eğitimi aldıktan sonra indüklenmiş radyoaktivite çalışmaları ile 1938 yılında Nobel Fizik Ödülü’nü kazandı. Stokholm’de Nobel Ödülü’nü alır almaz soluğu New York’ta aldı ve İtalya’ya bir daha dönmedi.***Enrico Fermi Şikago’da ilk nükleer reaktörü faaliyete geçirdi. Sonra da Manhattan Projesi’ne dahil oldu ve Los Alamos Ulusal Laboratuvarı’nda çalışmaya başladı. Atom bombasının yapımı ve Japonya’da patlatılmasıyla son bulan II. Dünya Savaşı’ndan sonra da Los Alamos Ulusal Laboratuvarı bilimde ve teknolojide yerini korudu. Bugün Los Alamos, dünyanın en büyük bilim ve teknoloji kurumlarından biridir. Ulusal güvenlik, uzay araştırmaları, nükleer füzyon, yenilenebilir enerji, tıp, nanoteknoloji ve süper bilgisayarlar gibi alanlarda çok disiplinli araştırmalar yürütmektedir.1950 yılında Enrico Fermi bilim insanı arkadaşlarıyla Los Alamos’ta öğle yemeğinde o sıralarda görülen bir UFO olayı tartışılırken şu soruyu sordu: “Herkes nerede?”. Burda herkesten kasıt dünya dışı akıllı canlılardı. İşte bu sorudan sonra uzaylılar mevzu bahis olunca bilim dilinde Fermi Paradoksu en önemli argümanlardan birisi oldu.Dünya dışı akıllı canlılar için bugün iki büyük fikir var. Bunlardan biri, galaksimizdeki uygarlıkların sayısını tahmin edebilen Drake Denklemi’dir. Diğeri ise, eğer burada herhangi bir yerde var olsaydı, zeki uzaylıları görmemiz gerektiğini iddia eden Fermi paradoksu.Galaksimizde 200 milyardan fazla yıldız var. Bunların içerisinden etrafında gezegen olan yıldızlar hesaba katıldığında tahmini gezegen sayısı yıldız sayısının birkaç katıdır. Bu durumda dünya dışı zeki hayatında ortaya çıkma ihtimalini çok düşük tuttuğumuzda bile yine de galaksimiz Samanyolu’nda çok sayıda uzaylı olmak zorundadır. Öte yandan Kepler Uzay Teleskobu’nun katkılarıyla 4 bine yakın öte gezegen keşfedilmiştir: Bu verileri inceleyen bilim insanları hayat olabilecek muhtemel gezegen sayısının 17 milyar civarında olabileceğini hesap etmektedirler.***Madem bu kadar uygarlık var, Enrico Fermi’nin sorusu şu: Öyleyse neredeler ve neden şimdiye kadar bir delil bulamadık?Bu soruya elliden fazla cevap verilmiş. Yıldızlar birbirlerine çok uzaklar iletişim kurmak çok zor ve zaman alır. Uzaylılar teknoloji olarak çok gelişmiş ve bizim içimizdeki savaşları, kavgaları görüp bizden uzak durmaya çalışıyor olabilirler. Beyin yapıları bizden birkaç basamak üstün olabilir. Mesela insanlar bir iş yapacakları zaman solucanlardan fikir danışmadıkları gibi, uzaylılar da bizi alt beyin olarak görüp bizimle iletişim kurmuyor olabilirler. Veya onlar bize sinyaller göndermişler fakat bizim teknolojimiz henüz algılayamıyor. Veya biz Matrix ve Truman Show gibi bilgisayar yazılımının içindeki figürleriz. Ya da bu kâinatta yalnınız ve kimsemiz yok, fakat biz birbirimizi öldürüp duruyoruz.Trump’ın uzay ordusuGeçen hafta ABD başkanı Trump Amerikan ordusunun 6. Kolu olarak Uzay Kuvvetleri’ni kurma talimatını verdi. Uzayda yaşayan çoğu Amerikalı üç-beş astronottan başka kimse şimdilik yok. Fakat uzay çalışmaları hızlı gelişiyor. Yakın zamanda çok sayıda yolcu uzay otellerine, Ay’a ve Mars’a gidecek. Peki bu kadar çok kişiyi kim uzaya götürecek?Los Angeles Belediye Başkanı Eric Garcetti SpaceX’e Los Angeles Limanı’nda Mars Mekiği yapma izni verdi. Mars Mekiği tam 100 kişiyi ve 150 ton kargoyu uzaya götürecek şekilde tasarlandı. Başkan Garcetti “Bu yıl bize birşey öğrettiyse o da büyük düşünmek ve ulaşılamayacak hayallerin peşinden gitmektir” dedi. Mars mekiği tam 16 katlı ve 19 katlı roket tarafından fırlatılacak ve yakıt olarak diğer gezegenlerde de kolayca elde edilebilen sıvı metan gazı kullanacak.Hal böyle olunca bir seferde 100 kişi uzaya gidebilecek. Tabiki bu insanlardan vergi toplayıp, asayişi sağlamak ve en önemlisi onlara demokrasi götürmek için güçlü bir orduya ihtiyaç olacak. Biz seçimlerle uğraşırken ABD uzaya ordu göndermek için kolları sıvamış durumda. ‘’Uzayda Amerikan hakimiyetine sahip olmak zorundayız’’ diyen Trump, uzay araştırmaları yapmak, uzay mekiği üretmek ve yeni roketler tasarlamak için öncülük etmek zorunda olduklarını belirtti. Vietnam’a, Afganistan’a, Irak’a ve diğer üçüncü Dünya ülkelerine demokrasi götüren ABD ordusu bakalım uzaya nasıl bir demokrasi getirecek? \n'

In [29]:
sp.select('h1.content-title')[0].text

'Herkes nerede?'

In [30]:
sp.select('article.article-content')[0].text

'\n\nLos Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine en yakın şehir ise 56 km uzaklıktaki Santa Fe. Los Alamos’ta hayatını devam ettirenler alışveriş ve eğlence için Santa Fe’ye gidip geliyorlar. Yıllar önce yolum Santa Fe’ye düşmüştü. Hazır buraya kadar gelmişken şu Los Alamos’u bir ziyaret edelim dedik. Fakat Santa Fe ziyaretim kızılderililerin yaz festivaline denk gelmişti ve otellerde yer yoktu. Geceyi Santa Fe’nin güneyindeki Albuquerque şehrinde geçirince Los Alamos’a gitmek kısmet olmadı.Peki Los Alamos kasabası bize neyi hatırlatıyor? Tabiki Atom bombasını. İlk atom bombasının yapımı ve test edilmesi ve II. Dünya Savaşı’nın bilimle sonlandırılması tam da bu kasabada bulunan Los Alamos Ulusal Laboratuvar’ında planlanıyor. Hal böyle olunca bu minik kasaba 1940’lardan günümüze kadar hep bilim insanlarını misafir etmiş ve uzun yıllar çoğu Nobel Ödülü sahibi binlerce bilim insanı burada yaşamışlar.\n***Los Alamos’ta yaşayan bu bilim insanlarının en önemlilerinden birisi de İtalyan bilim adamı Enrico Fermi idi. Enrico Fermi 1901 yılında Roma’da doğdu. Annesi ilkokul öğretmeni, babası ise demiryolları bakanlığında çalışıyordu. Atom bombasının babası olarak bilinen Fermi fizik eğitimi aldıktan sonra indüklenmiş radyoaktivite çalışmaları ile 1938 yılında Nobel Fizik Ödülü’nü kazandı. Stokholm’de Nobel Ödülü’nü alır almaz soluğu New York’ta aldı ve İtalya’ya bir daha dönmedi.***Enrico Fermi Şikago’da ilk nükleer reaktörü faaliyete geçirdi. Sonra da Manhattan Projesi’ne dahil oldu ve Los Alamos Ulusal Laboratuvarı’nda çalışmaya başladı. Atom bombasının yapımı ve Japonya’da patlatılmasıyla son bulan II. Dünya Savaşı’ndan sonra da Los Alamos Ulusal Laboratuvarı bilimde ve teknolojide yerini korudu. Bugün Los Alamos, dünyanın en büyük bilim ve teknoloji kurumlarından biridir. Ulusal güvenlik, uzay araştırmaları, nükleer füzyon, yenilenebilir enerji, tıp, nanoteknoloji ve süper bilgisayarlar gibi alanlarda çok disiplinli araştırmalar yürütmektedir.1950 yılında Enrico Fermi bilim insanı arkadaşlarıyla Los Alamos’ta öğle yemeğinde o sıralarda görülen bir UFO olayı tartışılırken şu soruyu sordu: “Herkes nerede?”. Burda herkesten kasıt dünya dışı akıllı canlılardı. İşte bu sorudan sonra uzaylılar mevzu bahis olunca bilim dilinde Fermi Paradoksu en önemli argümanlardan birisi oldu.Dünya dışı akıllı canlılar için bugün iki büyük fikir var. Bunlardan biri, galaksimizdeki uygarlıkların sayısını tahmin edebilen Drake Denklemi’dir. Diğeri ise, eğer burada herhangi bir yerde var olsaydı, zeki uzaylıları görmemiz gerektiğini iddia eden Fermi paradoksu.Galaksimizde 200 milyardan fazla yıldız var. Bunların içerisinden etrafında gezegen olan yıldızlar hesaba katıldığında tahmini gezegen sayısı yıldız sayısının birkaç katıdır. Bu durumda dünya dışı zeki hayatında ortaya çıkma ihtimalini çok düşük tuttuğumuzda bile yine de galaksimiz Samanyolu’nda çok sayıda uzaylı olmak zorundadır. Öte yandan Kepler Uzay Teleskobu’nun katkılarıyla 4 bine yakın öte gezegen keşfedilmiştir: Bu verileri inceleyen bilim insanları hayat olabilecek muhtemel gezegen sayısının 17 milyar civarında olabileceğini hesap etmektedirler.***Madem bu kadar uygarlık var, Enrico Fermi’nin sorusu şu: Öyleyse neredeler ve neden şimdiye kadar bir delil bulamadık?Bu soruya elliden fazla cevap verilmiş. Yıldızlar birbirlerine çok uzaklar iletişim kurmak çok zor ve zaman alır. Uzaylılar teknoloji olarak çok gelişmiş ve bizim içimizdeki savaşları, kavgaları görüp bizden uzak durmaya çalışıyor olabilirler. Beyin yapıları bizden birkaç basamak üstün olabilir. Mesela insanlar bir iş yapacakları zaman solucanlardan fikir danışmadıkları gibi, uzaylılar da bizi alt beyin olarak görüp bizimle iletişim kurmuyor olabilirler. Veya onlar bize sinyaller göndermişler fakat bizim teknolojimiz henüz algılayamıyor. Veya biz Matrix ve Truman Show gibi bilgisayar yazılımının içindeki figürleriz. Ya da bu kâinatta yalnınız ve kimsemiz yok, fakat biz birbirimizi öldürüp duruyoruz.Trump’ın uzay ordusuGeçen hafta ABD başkanı Trump Amerikan ordusunun 6. Kolu olarak Uzay Kuvvetleri’ni kurma talimatını verdi. Uzayda yaşayan çoğu Amerikalı üç-beş astronottan başka kimse şimdilik yok. Fakat uzay çalışmaları hızlı gelişiyor. Yakın zamanda çok sayıda yolcu uzay otellerine, Ay’a ve Mars’a gidecek. Peki bu kadar çok kişiyi kim uzaya götürecek?Los Angeles Belediye Başkanı Eric Garcetti SpaceX’e Los Angeles Limanı’nda Mars Mekiği yapma izni verdi. Mars Mekiği tam 100 kişiyi ve 150 ton kargoyu uzaya götürecek şekilde tasarlandı. Başkan Garcetti “Bu yıl bize birşey öğrettiyse o da büyük düşünmek ve ulaşılamayacak hayallerin peşinden gitmektir” dedi. Mars mekiği tam 16 katlı ve 19 katlı roket tarafından fırlatılacak ve yakıt olarak diğer gezegenlerde de kolayca elde edilebilen sıvı metan gazı kullanacak.Hal böyle olunca bir seferde 100 kişi uzaya gidebilecek. Tabiki bu insanlardan vergi toplayıp, asayişi sağlamak ve en önemlisi onlara demokrasi götürmek için güçlü bir orduya ihtiyaç olacak. Biz seçimlerle uğraşırken ABD uzaya ordu göndermek için kolları sıvamış durumda. ‘’Uzayda Amerikan hakimiyetine sahip olmak zorundayız’’ diyen Trump, uzay araştırmaları yapmak, uzay mekiği üretmek ve yeni roketler tasarlamak için öncülük etmek zorunda olduklarını belirtti. Vietnam’a, Afganistan’a, Irak’a ve diğer üçüncü Dünya ülkelerine demokrasi götüren ABD ordusu bakalım uzaya nasıl bir demokrasi getirecek? \n'

In [31]:
import pandas as pd

In [35]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp314-cp314-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Downloading lxml-6.1.1-cp314-cp314-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 2.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.1.1

In [36]:
df = pd.read_html('https://www.w3schools.com/html/html_tables.asp')[0]

In [37]:
df

                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

In [38]:
page=requests.get('https://www.karar.com/yazarlar/zafer-acar')

In [39]:
sp=soup(page.content, 'html.parser')

In [41]:
sp.prettify()

'<!DOCTYPE html>\n<html lang="tr">\n <head>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>\n  <meta content="width=device-width, initial-scale=1" name="viewport"/>\n  <title>\n   Zafer Acar - KARAR\n  </title>\n  <meta content="Zafer Acar tarafından KARAR için yazılan makaleler" name="description"/>\n  <link href="https://www.karar.com/yazarlar/zafer-acar" rel="canonical"/>\n  <meta content="website" property="og:type"/>\n  <meta content="KARAR" property="og:site_name"/>\n  <meta content="https://www.karar.com/yazarlar/zafer-acar" property="og:url"/>\n  <meta content="Zafer Acar" property="og:title"/>\n  <meta content="Zafer Acar tarafından KARAR için yazılan makaleler" property="og:description"/>\n  <meta content="https://cdn.karar.com/author/75_b.jpg" property="og:image"/>\n  <meta content="200" property="og:image:width"/>\n  <meta content="200" property="og:image:height"/>\n  <meta content="app-id=1009271502" name="apple-itunes-app"/>\n  <meta content="app-id=com.labdroids.karar" name="google-play-app"/>\n  <meta content="668763830688221" property="fb:app_id"/>\n  <link href="https://www.karar.com/service/rss.php" rel="alternate" type="application/rss+xml"/>\n  <meta content="max-snippet:-1, max-image-preview:large, max-video-preview:-1" name="robots"/>\n  <link href="/manifest.json" rel="manifest"/>\n  <link href="https://www.karar.com/d/assets/favicon/favicon.ico" rel="icon"/>\n  <meta content="CM News 6.0" name="generator"/>\n  <link href="https://www.karar.com/d/assets/bundle/karar-desktop-main.css?1771472334" rel="stylesheet"/>\n  <script>\n   const BURL = "https://www.karar.com/",\r\n\t\t\t\tDURL = "https://cdn.karar.com/";\n  </script>\n  <link href="https://cdn.karar.com/assets/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>\n  <link color="#e30613" href="https://cdn.karar.com/assets/favicon/safari-pinned-tab.svg" rel="mask-icon"/>\n  <meta content="#e30613" name="msapplication-TileColor"/>\n  <meta content="#ffffff" name="theme-color"/>\n  <meta content="fd13614ab1" name="Petal-Search-site-verification">\n   <!-- Google tag (gtag.js) -->\n   <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1L3TVQZ3LV">\n   </script>\n   <script>\n    window.dataLayer = window.dataLayer || [];\r\n  function gtag(){dataLayer.push(arguments);}\r\n  gtag(\'js\', new Date());\r\n\r\n  gtag(\'config\', \'G-1L3TVQZ3LV\');\n   </script>\n   <script>\n    !function(){var t=document.createElement("script");t.setAttribute("src",\'https://cdn.p.analitik.bik.gov.tr/tracker\'+(typeof Intl!=="undefined"?(typeof (Intl||"").PluralRules!=="undefined"?\'1\':typeof Promise!=="undefined"?\'2\':typeof MutationObserver!==\'undefined\'?\'3\':\'4\'):\'4\')+\'.js\'),t.setAttribute("data-website-id","d9b8fdca-5069-4cc2-b3f3-6ab32564a106"),t.setAttribute("data-host-url",\'//d9b8fdca-5069-4cc2-b3f3-6ab32564a106.collector.p.analitik.bik.gov.tr\'),document.head.appendChild(t)}();\n   </script>\n   <!-- Google Tag Manager / Karar GTM -->\n   <script>\n    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\r\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\r\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\r\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\r\n})(window,document,\'script\',\'dataLayer\',\'GTM-KXB9WDF9\');\n   </script>\n   <!-- End Google Tag Manager -->\n   <!--<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5668552793696977" crossorigin="anonymous"></script>-->\n   <script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js">\n   </script>\n   <script async="" src="https://cdn.adsby.io/headerbidding/adshb.prebid.js">\n   </script>\n   <script async="" src="https://cdn.adsby.io/karar/theadsiov2.js">\n   </script>\n   <script>\n    window.googletag = window.googletag || { cmd: [] };\r\n    \r\n    \r\n\tgoogletag.cmd.push(function ()\r\n\t{\r\n\t\tmappingFull = googletag.sizeMapping().\r\n\t\taddSize([1024, 360], [[970, 90], [1000, 250], [970, 250]]).\r\n\t\taddSize([768, 360], [[728, 250], [728, 90]]).\r\n\t\taddSize([360, 360], [[336, 280], [300, 250]]).\r\n\t\taddSize([0, 0], [[320, 100],[300, 100]]).\r\n\t\tbuild();\r\n\r\n\t\tmappingMiddle = googletag.sizeMapping().\r\n\t\taddSize([768, 360], [[670, 250], [640, 300], [336, 280], [300, 250], \'fluid\']).\r\n\t\taddSize([360, 360], [[336, 280], [300, 250]]).\r\n\t\taddSize([0, 0], [300, 250]).\r\n\t\tbuild();\r\n\r\n\t\tmappingSide = googletag.sizeMapping().\r\n\t\taddSize([360, 360], [[336, 280], [300, 250], \'fluid\']).\r\n\t\taddSize([0, 0], [300, 250]).\r\n\t\tbuild();\r\n\r\n\t\tmappingSticky = googletag.sizeMapping().\r\n\t\taddSize([1024, 360], [970, 90]).\r\n\t\taddSize([768, 360], [728, 90]).\r\n\t\taddSize([0, 0], [[300, 100],[320,100]]).\r\n\t\tbuild();\r\n\r\n\t\tmappingPageSkin = googletag.sizeMapping().\r\n\t\taddSize([1720, 600], [[300, 600],[160, 600],[120, 600]]).\r\n\t\taddSize([1520, 600], [[160, 600],[120, 600]]).\r\n\t\taddSize([1440, 600], [[160, 600],[120, 600]]).\r\n\t\taddSize([1366, 600], [[120, 600]]).\r\n\t\taddSize([0, 0], []).\r\n\t\tbuild();\r\n\r\n\t\tmappingMobilM = googletag.sizeMapping().\r\n\t\taddSize([0, 0], [[300, 50], [320, 100], [320, 50], [300, 100]]).\r\n\t\tbuild();\r\n\t\tmappingMobilSC = googletag.sizeMapping().\r\n\t\taddSize([0, 0], [[300,250], [336, 280]]).\r\n\t\tbuild();\r\n    \r\n        googletag.setConfig({ disableInitialLoad: true });\r\n        googletag.setConfig({ singleRequest: true });\r\n\t\tgoogletag.enableServices();\r\n\t});\n   </script>\n   <script async="" src="https://jsc.idealmedia.io/site/839414.js">\n   </script>\n   <style>\n    .article-detail .google-auto-placed{\r\n        margin-bottom: 30px;\r\n    }\n   </style>\n  </meta>\n </head>\n <body class="body-main cat-author author-article author">\n  <header class="main-header">\n   <div class="top">\n    <div class="container">\n     <div class="date">\n      07 Haziran 2026 Pazar\n     </div>\n     <div class="currency">\n      <div class="item down">\n       <span class="text">\n        Altın\n       </span>\n       <i class="icon icon-down-dir">\n       </i>\n       <span class="value">\n        6408.33\n       </span>\n       <span class="rate">\n        %0\n       </span>\n      </div>\n      <div class="item down">\n       <span class="text">\n        BIST\n       </span>\n       <i class="icon icon-down-dir">\n       </i>\n       <span class="value">\n        13694.19\n       </span>\n       <span class="rate">\n        %0\n       </span>\n      </div>\n      <div class="item down">\n       <span class="text">\n        Dolar\n       </span>\n       <i class="icon icon-down-dir">\n       </i>\n       <span class="value">\n        45.9704\n       </span>\n       <span class="rate">\n        %0\n       </span>\n      </div>\n      <div class="item down">\n       <span class="text">\n        Euro\n       </span>\n       <i class="icon icon-down-dir">\n       </i>\n       <span class="value">\n        53.01\n       </span>\n       <span class="rate">\n        %0\n       </span>\n      </div>\n     </div>\n     <div class="social">\n      <a class="youtube" href="https://www.youtube.com/channel/UCoLyFzOzAzNG_-oR-O4relg?sub_confirmation=1" rel="nofollow noopener noreferrer" target="_blank" title="Youtube ile takip et">\n       <i class="icon icon-youtube-play">\n       </i>\n      </a>\n      <a class="instagram" href="https://www.instagram.com/kararhaber" rel="nofollow noopener noreferrer" target="_blank" title="İnstagram ile takip et">\n       <i class="icon icon-instagramm">\n       </i>\n      </a>\n      <a class="facebook" href="https://www.facebook.com/KararHaber" rel="nofollow noopener noreferrer" target="_blank" title="Facebook ile takip et">\n       <i class="icon icon-facebook">\n       </i>\n      </a>\n      <a class="twitter" href="https://twitter.com/KararHaber" rel="nofollow noopener noreferrer" target="_blank" title="Twitter ile takip et">\n       <i class="icon icon-twitter">\n       </i>\n      </a>\n     </div>\n    </div>\n   </div>\n   <div class="center">\n    <div class="container">\n     <div class="logo relative">\n      <a href="https://www.karar.com/" rel="home" title="KARAR">\n       <img alt="KARAR" class="lazy" height="60" loading="lazy" src="https://www.karar.com/d/assets/logo-white.svg" width="233"/>\n      </a>\n     </div>\n     <div class="flex middle">\n      <form action="/ara" method="get">\n       <div class="search-wrapper flex middle">\n        <input class="search-input" name="key" placeholder="Aranacak kelime" type="text"/>\n        <i class="icon icon-search">\n        </i>\n       </div>\n      </form>\n      <div class="weather flex middle">\n       <i class="icon icon-accu-1">\n       </i>\n       <span class="value">\n        25°\n       </span>\n       <div class="parameter margin-left-md">\n        <div class="city">\n         İstanbul\n        </div>\n        <div>\n         Güneşli\n        </div>\n       </div>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="main-nav">\n    <div class="container">\n     <ul class="flex middle">\n      <li>\n       <a alt="Anasayfa" href="/">\n        <i class="icon-home">\n        </i>\n       </a>\n      </li>\n      <li>\n       <a alt="Güncel" href="/guncel-haberler">\n        Güncel\n       </a>\n      </li>\n      <li>\n       <a alt="Yazarlar" href="/yazarlar">\n        Yazarlar\n       </a>\n      </li>\n      <li>\n       <a alt="Dünya" href="/dunya-haberleri">\n        Dünya\n       </a>\n      </li>\n      <li>\n       <a alt="Ekonomi" href="/ekonomi-haberleri">\n        Ekonomi\n       </a>\n      </li>\n      <li>\n       <a alt="Spor" href="/spor-haberleri">\n        Spor\n       </a>\n      </li>\n      <li>\n       <a alt="Hayat" href="/hayat-haberleri">\n        Hayat\n       </a>\n      </li>\n      <li>\n       <a alt="Karar Video" href="/karar-tv">\n        Karar Video\n       </a>\n      </li>\n      <li>\n       <a alt="Görüşler" href="/gorusler">\n        Görüşler\n       </a>\n      </li>\n      <li>\n       <a alt="Resmi İlanlar" href="/resmi-ilanlar">\n        Resmi İlanlar\n       </a>\n      </li>\n      <li>\n       <a alt="Kültür Sanat" href="/kultur-sanat-haberleri">\n        Kültür Sanat\n       </a>\n      </li>\n      <li>\n       <a aria-label="Menu" class="menu show-all-menu" href="#">\n        <i class="icon-menu">\n        </i>\n       </a>\n      </li>\n     </ul>\n    </div>\n   </div>\n  </header>\n  <div class="last-news">\n   <div class="container flex middle">\n    <div class="block-title">\n     <a href="/son-dakika">\n      SON DAKİKA :\n     </a>\n    </div>\n    <div class="news-content">\n     <div class="swiper-container">\n      <div class="swiper-wrapper">\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/manisada-is-faciasi-dokum-makinesine-sikisan-isci-hayatini-kaybetti-2052324">\n         Manisa\'da iş faciası! Döküm makinesine sıkışan işçi hayatını kaybetti\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/tbmmde-yogun-hafta-toprak-koruma-ve-arazi-kullanimi-kanun-teklifi-2052323">\n         TBMM\'de yoğun hafta: Toprak koruma ve arazi kullanımı kanun teklifi görüşülecek\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/nato-zirvesi-izni-ne-zaman-baslayacak-ve-bitecek-ankarada-nato-zirvesi-2052321">\n         Ankaralılar dikkat! 6-12 Temmuz haftasında kamuya bir hafta izin ve yasaklar geldi: Kimler izinli, neler yasak?\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/ak-parti-genel-baskan-yardimcisi-yazici-acikladi-yeni-anayasa-icin-son-2052320">\n         AK Parti Genel Başkan Yardımcısı Yazıcı açıkladı:  Yeni anayasa için son karar referandum olacak\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/ozel-cephesinden-dsp-iddialarina-cevap-chpyi-saraya-teslim-etmeyecegiz-2052318">\n         Özel cephesinden DSP iddialarına cevap: CHP’yi Saray’a teslim etmeyeceğiz\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/otokoc-genel-mudurlugune-silahli-saldiri-genel-baskan-inan-ekici-mi-2052317">\n         Otokoç Genel Müdürlüğü\'ne silahlı saldırı: Genel Başkan İnan Ekici mi hedef, Rahmi Koç mu?\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/can-polat-cinayetinde-4-supheli-adliyeye-sevk-edildi-2052315">\n         Can Polat cinayetinde 4 şüpheli adliyeye sevk edildi\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/avcilarda-korkutan-olay-3-katli-binanin-kolonu-yan-binanin-odasina-dustu-2052314">\n         Avcılar\'da korkutan olay! 3 katlı binanın kolonu yan binanın odasına düştü\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/akom-acikladi-istanbulda-yeni-haftada-yagis-beklenmiyor-2052313">\n         AKOM açıkladı: İstanbul\'da yeni haftada yağış beklenmiyor\n        </a>\n       </div>\n       <div class="swiper-slide flex middle">\n        <a class="news-title" href="/guncel-haberler/pendikte-yol-verme-kavgasi-kaputu-acip-aracim-ariza-yapti-dedi-polisi-2052309">\n         Pendik’te yol verme kavgası: Kaputu açıp \'aracım arıza yaptı\' dedi, polisi arayınca ikna oldu\n        </a>\n       </div>\n      </div>\n     </div>\n    </div>\n   </div>\n  </div>\n  <section class="breadcrumbs">\n   <div class="container">\n    <ol>\n     <li>\n      <a href="https://www.karar.com/">\n       <span>\n        <i class="icon-home">\n        </i>\n        Anasayfa\n       </span>\n      </a>\n     </li>\n     <li>\n      <a href="https://www.karar.com/yazarlar">\n       <span>\n        Yazarlar\n       </span>\n      </a>\n     </li>\n     <li>\n      <span>\n       Zafer Acar\n      </span>\n     </li>\n    </ol>\n   </div>\n  </section>\n  <main role="main">\n   <div class="banner-pageskin container">\n    <div class="pageskin-left">\n     <div class="fixed">\n      <the-ads data-adunit="/karar.com/karar_desktop_pageskin_L" data-device="desktop" data-sizes="[[120, 240], [120, 600]]">\n      </the-ads>\n     </div>\n    </div>\n    <div class="pageskin-right">\n     <div class="fixed">\n      <the-ads data-adunit="/karar.com/karar_desktop_pageskin_R" data-device="desktop" data-sizes="[[160, 600], [120, 240], [120, 600]]">\n      </the-ads>\n     </div>\n    </div>\n   </div>\n   <div class="container section-padding-gutter">\n    <section class="banner banner-wide">\n     <the-ads data-adunit="/karar.com/karar_desktop_masthead" data-device="desktop" data-sizes="[[728, 90], [970, 250], [970, 90], [1000, 250], \'fluid\']" style="\r\n    display:block; \r\nheight:250px;\r\noverflow: hidden; \r\nposition: relative;\r\n">\n     </the-ads>\n    </section>\n    <div class="page-content author-page">\n     <div class="author-info box-shadow">\n      <header class="w-100">\n       <a href="/yazarlar">\n        Bugünkü Yazarlar\n       </a>\n       <a href="/yazarlar#tumu">\n        Tüm Yazarlar\n       </a>\n      </header>\n      <div class="image r1x1">\n       <img alt="Zafer Acar" src="https://cdn.karar.com/author/75_b.jpg"/>\n      </div>\n      <div class="info">\n       <h1 class="name">\n        Zafer Acar\n       </h1>\n       <div class="mb-2">\n        <span data-erot="mnsrenpne@xnene.pbz">\n        </span>\n       </div>\n      </div>\n      <div class="author-social social">\n       <a href="https://www.facebook.com/KararHaber " rel="nofollow noopener" target="_blank">\n        <i class="icon-facebook">\n        </i>\n       </a>\n       <a href="https://twitter.com/zaferNasa" rel="nofollow noopener" target="_blank">\n        <i class="icon-twitter">\n        </i>\n       </a>\n       <a href="https://www.instagram.com/kararhaber" rel="nofollow noopener" target="_blank">\n        <i class="icon-instagramm">\n        </i>\n       </a>\n      </div>\n     </div>\n     <script>\n      document.addEventListener("cmready", function()\n\t{\n\t\t$(\'[data-erot]\').each(function()\n\t\t{\n\t\t\tlet elm = $(this);\n\t\t\t$(this).replaceWith(\'<a href="mailto:\' + elm.attr(\'data-erot\').replace(/[a-zA-Z]/g, function(c)\n\t\t\t{\n\t\t\t\treturn String.fromCharCode((c <= "Z" ? 90 : 122) >= (c = c.charCodeAt(0) + 13) ? c : c - 26);\n\t\t\t}) + \'"><i class="icon-mail"></i></a>\')\n\t\t})\n\t});\n     </script>\n     <div class="row">\n      <div class="col-8">\n       <div class="page-caption mb-2">\n        Yazarın Yazıları\n       </div>\n       <section class="author-article">\n        <article class="item box-shadow">\n         <a href="/yazarlar/zafer-acar/engellilerin-umudu-yapay-zeka-1590090">\n          <h3>\n           Engellilerin umudu yapay zeka\n          </h3>\n          <p>\n           Yapay zeka her alanda büyük değişimler ve gelişimler vaad ediyor. Almanya’da yapılan yeni bir araştırma, görme engelli vatandaşlarımızın...\n          </p>\n         </a>\n         <time datetime="2021-07-19 00:23:00">\n          19.07.2021\n         </time>\n        </article>\n        <article class="item box-shadow">\n         <a href="/yazarlar/zafer-acar/kuantum-yapay-zeka-1590019">\n          <h3>\n           Kuantum yapay zeka\n          </h3>\n          <p>\n           Teknolojik gelişmeler baş döndürücü hızla ilerliyor. Önümüzdeki 30 yıl yapay zeka yılı olacak derken, kuantum bilgisayarlar büyük bir ilerleme...\n          </p>\n         </a>\n         <time datetime="2021-07-12 00:06:00">\n          12.07.2021\n         </time>\n        </article>\n        <article class="item box-shadow">\n         <a href="/yazarlar/zafer-acar/astronot-001-1589950">\n          <h3>\n           Astronot 001\n          </h3>\n          <p>\n           Uzay çalışmaları ve uçuşları küçüklüğümden beri hep ilgimi çekmiştir. Özellikle son 12 yıldır nerede bir astronomi etkinliği olursa,...\n          </p>\n         </a>\n         <time datetime="2021-07-05 00:09:00">\n          05.07.2021\n         </time>\n        </article>\n        <article class="item box-shadow">\n         <a href="/yazarlar/zafer-acar/cinin-uzay-programi-tam-gaz-1589817">\n          <h3>\n           Çin’in uzay programı tam gaz\n          </h3>\n          <p>\n           Uzay çalışmalarında ne kadar ileride iseniz, bilim ve teknolojide de o kadar ilerler ve Dünya’da bilim ve teknolojinin öncüsü olur ve ekonomik...\n          </p>\n         </a>\n         <time datetime="2021-06-21 00:10:00">\n          21.06.2021\n         </time>\n        </article>\n        <article class="item box-shadow">\n         <a href="/yazarlar/zafer-acar/yapay-zeka-ile-cip-tasarimi-1589750">\n          <h3>\n           Yapay zeka ile çip tasarımı\n          </h3>\n          <p>\n           Geçtiğimiz hafta Google, bilgisayar çiplerini insanlardan daha hızlı tasarlayabilen bir yapay zeka geliştirdiğini duyurdu. Yapay zeka, makine öğrenmesi,...\n          </p>\n         </a>\n         <time datetime="2021-06-14 00:05:00">\n          14.06.2021\n         </time>\n        </article>\n        <article class="item box-shadow">\n         <a href="/yazarlar/zafer-acar/venusun-iki-ziyaretcisi-1589681">\n          <h3>\n           Venüs’ün iki ziyaretçisi\n          </h3>\n          <p>\n           Geçtiğimiz hafta NASA, atmosferini ve jeolojik özelliklerini incelemek için 2028 ve 2030 yılları arasında, iki yeni misyonla Venüs gezegenine çıkarma...\n          </p>\n         </a>\

In [42]:
linkler=sp.find_all('article',{'class':'item box-shadow'})

In [43]:
linkler

[<article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/engellilerin-umudu-yapay-zeka-1590090">
 <h3>Engellilerin umudu yapay zeka</h3>
 <p>Yapay zeka her alanda büyük değişimler ve gelişimler vaad ediyor. Almanya’da yapılan yeni bir araştırma, görme engelli vatandaşlarımızın...</p>
 </a>
 <time datetime="2021-07-19 00:23:00">19.07.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/kuantum-yapay-zeka-1590019">
 <h3>Kuantum yapay zeka</h3>
 <p>Teknolojik gelişmeler baş döndürücü hızla ilerliyor. Önümüzdeki 30 yıl yapay zeka yılı olacak derken, kuantum bilgisayarlar büyük bir ilerleme...</p>
 </a>
 <time datetime="2021-07-12 00:06:00">12.07.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/astronot-001-1589950">
 <h3>Astronot 001</h3>
 <p>Uzay çalışmaları ve uçuşları küçüklüğümden beri hep ilgimi çekmiştir. Özellikle son 12 yıldır nerede bir astronomi etkinliği olursa,...</p>
 </a>
 <time datetime="2021-07-05 00:09:00">05.07.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/cinin-uzay-programi-tam-gaz-1589817">
 <h3>Çin’in uzay programı tam gaz</h3>
 <p>Uzay çalışmalarında ne kadar ileride iseniz, bilim ve teknolojide de o kadar ilerler ve Dünya’da bilim ve teknolojinin öncüsü olur ve ekonomik...</p>
 </a>
 <time datetime="2021-06-21 00:10:00">21.06.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zeka-ile-cip-tasarimi-1589750">
 <h3>Yapay zeka ile çip tasarımı</h3>
 <p>Geçtiğimiz hafta Google, bilgisayar çiplerini insanlardan daha hızlı tasarlayabilen bir yapay zeka geliştirdiğini duyurdu. Yapay zeka, makine öğrenmesi,...</p>
 </a>
 <time datetime="2021-06-14 00:05:00">14.06.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/venusun-iki-ziyaretcisi-1589681">
 <h3>Venüs’ün iki ziyaretçisi</h3>
 <p>Geçtiğimiz hafta NASA, atmosferini ve jeolojik özelliklerini incelemek için 2028 ve 2030 yılları arasında, iki yeni misyonla Venüs gezegenine çıkarma...</p>
 </a>
 <time datetime="2021-06-07 00:01:00">07.06.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zeka-ile-gercekci-oyun-grafikleri-1589609">
 <h3>Yapay zeka ile gerçekçi oyun grafikleri</h3>
 <p>Yıllar yıllar önce, daha bilgisayarlarımız yokken, arkadaşlarımız bilgisayarda oyun oynar, biz de saatlerce onları izlerdik. Sonra oyuna dahil...</p>
 </a>
 <time datetime="2021-05-31 00:33:00">31.05.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zeka-is-dunyasini-derinden-sarsiyor-1589535">
 <h3>Yapay zeka iş dünyasını derinden sarsıyor</h3>
 <p>Yapay zeka (AI) teknolojisi, tüm iş sektörlerine nüfuz ederek büyük değişimlere sebep oluyor. Dijital dönüşümünü sağlamış, sağlam ve...</p>
 </a>
 <time datetime="2021-05-24 00:29:00">24.05.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/kariyerinize-yapay-zekayi-ekleyin-1589470">
 <h3>Kariyerinize yapay zekayı ekleyin</h3>
 <p>Yapay zeka her alanda ciddi ilerlemeler kaydetti. Sağlıkta, bilim ve teknolojide, askeri alanlarda, tarımda, eğitimde, gazetecilikte, hukukta, bankacılıkta,...</p>
 </a>
 <time datetime="2021-05-17 00:14:00">17.05.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zeka-ogrenmek-hic-bu-kadar-kolay-olmamisti-1589397">
 <h3>Yapay zeka öğrenmek hiç bu kadar kolay olmamıştı</h3>
 <p>Son zamanlarda yapay zeka öğrenmek isteyen yüzlerce kişiden değişik emailler alıyorum. Çoğu bir kitap tavsiyesi veya kaynak soruyor. Hepsine tek...</p>
 </a>
 <time datetime="2021-05-10 00:01:00">10.05.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/spacex-bu-isi-biliyor-1589251">
 <h3>SpaceX bu işi biliyor</h3>
 <p>Geçtiğimiz hafta NASA ve SpaceX ilk defa daha önce kullanılmış bir roket ile daha önce kullanılmış bir uzay aracını Uluslararası Uzay İstasyonu’na...</p>
 </a>
 <time datetime="2021-04-26 00:11:00">26.04.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/butun-evren-bir-yapay-zeka-algoritmasi-mi-1589178">
 <h3>Bütün evren bir yapay zekâ algoritması mı?</h3>
 <p>Geçtiğimiz hafta, Microsoft için çalışan fizikçiler yayınladıkları bir akademik makalede içinde yaşadığımız evrenin bir makine öğrenmesi...</p>
 </a>
 <time datetime="2021-04-19 00:17:00">19.04.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zekasiz-dijital-donusum-1589106">
 <h3>Yapay zekâsız dijital dönüşüm</h3>
 <p>On sekiz yıl Los Angeles’ta yaşadıktan sonra, üniversitedeki derslerin dijital ortamda yapılmasını fırsat bilerek 5 aylığına Türkiye’de...</p>
 </a>
 <time datetime="2021-04-12 00:05:00">12.04.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/cocuklar-icin-yapay-zeka-1589037">
 <h3>Çocuklar için yapay zekâ</h3>
 <p>Son 2 yıldır ilköğretim okullarında, liselerde ve üniversitelerde davet üzerine yapay zekâ üzerine konuşuyorum. İlk başlarda sorular yapay...</p>
 </a>
 <time datetime="2021-04-05 00:10:00">05.04.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zekayi-ne-yapmali-1588967">
 <h3>Yapay zekâyı ne yapmalı?</h3>
 <p>Son bir kaç gündür Konya’da iş insanları ile yapay zekâ üzerine konuşmalarımız oldu. Kendilerine yapay zekânın nimetlerini anlatmaya çalıştım....</p>
 </a>
 <time datetime="2021-03-29 00:28:00">29.03.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zekanin-yildizlari-1588897">
 <h3>Yapay zekânın yıldızları</h3>
 <p>Her alanın kendine göre en iyileri vardır. Filmin Oscar Ödülleri, gazetecilerin Pulitzer Ödülleri, Bilimsel araştırmaların Nobel Ödülü. Yapay...</p>
 </a>
 <time datetime="2021-03-22 00:28:00">22.03.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/geveze-yapay-zeka-1588765">
 <h3>Geveze yapay zekâ</h3>
 <p>İnsanın çok konuşanına geveze deniyor. Peki ya makinenin çok konuşanına ne diyeceğiz? Türk astronot için isim belirleme çalışmaları devam...</p>
 </a>
 <time datetime="2021-03-08 00:07:00">08.03.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zekanin-urettigi-sahte-insanlar-1588696">
 <h3>Yapay zekânın ürettiği sahte insanlar</h3>
 <p>Şikago’lu gazeteci Sydney J. Harris “İnsanların yaptığı sahte paralardan çok, paraların yaptığı sahte insan vardır” der. 2014 yılında...</p>
 </a>
 <time datetime="2021-03-01 00:09:00">01.03.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/eller-marsa-biz-aya-1588628">
 <h3>Eller Mars’a, biz Ay’a</h3>
 <p>Bu yıl Şubat ayı uzay çalışmaları açısından bereketli bir ay oldu. Türkiye Uzay Ajansı geçtiğimiz hafta Ay’ı hedef almış ve 2023 yılında...</p>
 </a>
 <time datetime="2021-02-22 00:08:00">22.02.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/milli-uzay-programi-1588559">
 <h3>Milli Uzay Programı</h3>
 <p>Geçtiğimiz hafta en önemli gelişme şüphesiz Türkiye’nin Milli Uzay Programı’nın açıklanması oldu. Bu köşede yaklaşık üç senedir astronomi,...</p>
 </a>
 <time datetime="2021-02-15 00:12:00">15.02.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zeka-caginda-ask-1588496">
 <h3>Yapay zekâ çağında aşk</h3>
 <p>Yapay zekâ 21. yüzyılın vazgeçilmez bir aracı ve her alanda en yakın dostumuz olmaya devam ediyor. Her taşın altından çıkan ve her işe el...</p>
 </a>
 <time datetime="2021-02-08 00:04:00">08.02.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/30-gunde-yapay-zeka-1588433">
 <h3>30 günde yapay zekâ</h3>
 <p>Her şey birkaç ay önce aldığım bir email ile başladı. Ege Üniversitesi, IEEE Öğrenci Topluluğu, Robotic Automation Society’den bir grup öğrenci...</p>
 </a>
 <time datetime="2021-02-01 00:23:00">01.02.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/siber-guvenlik-ve-yapay-zeka-1588362">
 <h3>Siber güvenlik ve yapay zekâ</h3>
 <p>Günümüzde insanların her attığı adım, yaptığı her alışveriş, toplum önünde yaptığı her konuşma ve daha sayamadığımız her hareketi...</p>
 </a>
 <time datetime="2021-01-25 00:26:00">25.01.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/trilyon-parametreli-yapay-zeka-1588297">
 <h3>Trilyon parametreli yapay zekâ</h3>
 <p>Geçtiğimiz yaz OpenAI şirketi GPT3 (Generative Pretrained Transformer) ismini verdiği bir doğal dil işleme modelini duyurmuş ve makine öğrenmesi...</p>
 </a>
 <time datetime="2021-01-18 00:17:00">18.01.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/verilerimiz-ne-kadar-guvende-1588225">
 <h3>Verilerimiz ne kadar güvende?</h3>
 <p>Florida Eyaleti’nin Riviera isimli şehrinde polis istasyonuna bir email geldi. Bu emailin ekinde bir dosya vardı ve polis istasyonunda emaillere bakan...</p>
 </a>
 <time datetime="2021-01-11 00:16:00">11.01.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/akilli-makineler-ile-omuz-omuza-1588157">
 <h3>Akıllı makineler ile  omuz omuza</h3>
 <p>Nesnelerin İnterneti, kısa adıyla IoT, ile makineler hızla akıllı hale geliyor. Makineler akıllandıkça insanların beğenmediği rutin işler...</p>
 </a>
 <time datetime="2021-01-04 00:31:00">04.01.2021</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/ayda-yapay-zeka-1588094">
 <h3>Ay’da yapay zekâ</h3>
 <p>Çin her konuda ABD’de ile kıyasıya bir yarış halinde ve aynı zamanda ekonomik olarak Dünya’nın en güçlü ülkesi olma yolunda büyük bir...</p>
 </a>
 <time datetime="2020-12-28 00:26:00">28.12.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/2021de-yapay-zeka-1588030">
 <h3>2021’de yapay zekâ</h3>
 <p>Bu yıl her açıdan karmaşık ve ilginç bir yıl olarak tarihe geçti. COVID-19 salgını sebebiyle ertelenen dijital dönüşümü işletmeler ve kamu...</p>
 </a>
 <time datetime="2020-12-21 00:48:00">21.12.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/super-askerler-biyonik-insanlar-1587965">
 <h3>Süper askerler, biyonik insanlar</h3>
 <p>ABD istihbarat birimlerinin yayınladığı bir rapora göre, Çin askeri birimleri biyolojik olarak geliştirilmiş, DNA’sı değiştirilmiş süper...</p>
 </a>
 <time datetime="2020-12-14 00:12:00">14.12.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/cinin-yapay-gunesi-1587901">
 <h3>Çin’in “Yapay Güneş’i”</h3>
 <p>Çin Devleti ileri düzey teknolojilerde ABD ile kıyasıya bir yarışa  girdi. Bilim ve teknoloji konusunda sıradışı mesafe kat eden Çin, her alanda...</p>
 </a>
 <time datetime="2020-12-07 00:29:00">07.12.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/2050de-isci-bayrami-1587835">
 <h3>2050’de işçi bayramı</h3>
 <p>Bu yazımızda yapay zekânın sahip olduğu geleceğe bir göz atmaya çalışacağız. Yapay zekâ insanların yaptığı rutin işleri ellerinden almaya...</p>
 </a>
 <time datetime="2020-11-30 00:20:00">30.11.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/uzay-istasyonunun-20-yili-1587705">
 <h3>Uzay İstasyonu’nun 20 yılı</h3>
 <p>Tam 20 yıl önce, 2 Kasım 2000 tarihinde iki Rus Kozmonot ve bir NASA Astronotu Uluslararası Uzay İstasyonu’na adım attı. O günden bu yana istasyon...</p>
 </a>
 <time datetime="2020-11-16 00:22:00">16.11.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zekanin-yalani-1587637">
 <h3>Yapay zekânın yalanı</h3>
 <p>Hiç yalan söylemek zorunda kaldınız mı? Bize şartlar ne olursa olsun, aleyhimize bile olsa, doğruyu söylememiz öğretildi. Ancak bilimsel araştırmaların...</p>
 </a>
 <time datetime="2020-11-09 00:22:00">09.11.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/matematik-yerine-yapay-zeka-1587577">
 <h3>Matematik yerine yapay zekâ</h3>
 <p>Facebook sembolik akıl yürütmeyi kullanarak gelişmiş matematik denklemlerini çözebilen yeni bir yapay zekâ algoritması geliştirdi. Bu uygulama...</p>
 </a>
 <time datetime="2020-11-02 00:29:00">02.11.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/turkiye-yapay-zeka-haftasi-1587510">
 <h3>Türkiye Yapay Zekâ Haftası</h3>
 <p>Geçtiğimiz hafta Türkiye Yapay Zeka İnisiyatifi’nin düzenlediği Türkiye Yapay Zekâ Haftası (TR AI Week) konuşmalarının birçoğunu dinleme...</p>
 </a>
 <time datetime="2020-10-26 00:45:00">26.10.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/git-gel-uzay-6-saat-1587442">
 <h3>Git gel uzay 6 saat</h3>
 <p>Rus Uzay Ajansı Roscosmos, geçtiğimiz 14 Ekim  Çarşamba günü, yeni model uzay aracıyla Uluslararası Uzay İstasyonu’na 3 saat gibi çok kısa...</p>
 </a>
 <time datetime="2020-10-19 00:09:00">19.10.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/astronomide-yapay-zeka-uygulamalari-1587379">
 <h3>Astronomide yapay zekâ uygulamaları</h3>
 <p>Hayatımda en çok sevdiğim iki alan astronomi ve yapay zekâdır. Birisine yoğunlaşınca diğerini ihmal ettiğimi düşünüp hemen bir projeyle veya...</p>
 </a>
 <time datetime="2020-10-12 00:39:00">12.10.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/nasanin-23-milyon-dolarlik-tuvaleti-1587313">
 <h3>NASA’nın 23 milyon dolarlık tuvaleti</h3>
 <p>Bu yazı bilimsel olmasına rağmen biraz iğrenç. O yüzden herkese uygun olmayabilir. Geçtiğimiz cuma günü NASA Cygnus uzay aracı ile Uluslararası...</p>
 </a>
 <time datetime="2020-10-05 00:28:00">05.10.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yalnizim-dostlarim-1587249">
 <h3>Yalnızım dostlarım</h3>
 <p>Kaliforniya Üniversitesi San Diego Tıp Fakültesi bilim insanları tarafından yürütülen yeni bir bilimsel araştırmada yapay zekânın insanların...</p>
 </a>
 <time datetime="2020-09-28 00:34:00">28.09.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/venusun-atmosferinde-hayat-izleri-1586411">
 <h3>Venüs’ün atmosferinde hayat izleri</h3>
 <p>Bir yılı bir gününden kısa, ters, hassas, çetin ceviz ve sıcak gezegen: Venüs.Geçtiğimiz hafta bilim insanlarını çok heyecanlandıran ve şaşırtan...</p>
 </a>
 <time datetime="2020-09-21 00:23:00">21.09.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/uzaktan-egitimle-universiteler-devre-disi-1585193">
 <h3>Uzaktan eğitimle üniversiteler devre dışı</h3>
 <p>Birkaç gün önce bende otonom araçlarla alakalı bir merak başladı.Çocukluğumda hayranlıkla izlediğim ‘Kara Şimşek’ dizisindeki araç gibi...</p>
 </a>
 <time datetime="2020-09-14 00:32:00">14.09.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/bos-zamaniniza-talibim-1584098">
 <h3>Boş zamanınıza talibim</h3>
 <p>Newton mekaniğine göre zaman her yerde aynıdır. Yani zaman herkes için aynı işler.Fakat Einstein için herkesin zamanı farklıdır ve lokaldir....</p>
 </a>
 <time datetime="2020-09-07 00:33:00">07.09.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yoneticiler-ve-is-insanlari-icin-yapay-zek-1582951">
 <h3>Yöneticiler ve iş insanları için yapay zekâ</h3>
 <p>Yapay zekâ, makine öğrenmesi ve veri bilimi heyecan verici gelişmelere sahne oluyor.Yapat zekâ kamu kurum ve kuruluşlari ve özel sektörde inanılmaz...</p>
 </a>
 <time datetime="2020-08-31 02:39:00">31.08.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yeniden-baslasaydim-1581630">
 <h3>Yeniden başlasaydım</h3>
 <p>Yapay zekâ her geçen gün daha fazla önem kazanıyor.İş ilanlarında artık yapay zekâ bilen veri bilimcileri arayan şirketlerin sayısında ciddi...</p>
 </a>
 <time datetime="2020-08-24 00:44:00">24.08.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/humanoidlerle-evlenir-miydiniz-1580348">
 <h3>Humanoidlerle evlenir miydiniz?</h3>
 <p>Humanoidleri insan mı yoksa robot mu olduğunu ayırt edemediğimiz insansı robotlar olarak tanımlayabiliriz.Yapay zekâ her alanda kendisini hissettiriyor....</p>
 </a>
 <time datetime="2020-08-17 00:41:00">17.08.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/yapay-zek-bilgisayar-programciligini-bitirdi-mi-1579208">
 <h3>Yapay zekâ bilgisayar programcılığını bitirdi mi?</h3>
 <p>Son birkaç haftadır yapay zekâ dünyası, yapay zekânın insanlığın sonunu getireceğini iddia eden Elon Musk’un kurduğu ve desteklediği OpenAI...</p>
 </a>
 <time datetime="2020-08-10 00:28:00">10.08.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/bulut-bilisim-ile-tanisin-1578162">
 <h3>Bulut Bilişim ile tanışın</h3>
 <p>Yıl 1994. İnternet iş modellerinin yeni yeni patlama yaptığı yıllar.Zamanın genç girişimcilerinden Jeffrey Preston Bezos, internet iş modelleri...</p>
 </a>
 <time datetime="2020-08-03 00:31:00">03.08.2020</time>
 </article>,
 <article class="item box-shadow">
 <a href="/yazarlar/zafer-acar/beklenen-gelecek-geldi-1577019">
 <h3>Beklenen gelecek geldi</h3>
 <p>Yaklaşık altı aylık bir aradan sonra yeniden Karar Gazetesi okurlarıyla buluşmanın heyecanını yaşıyorum.Ocak ayında sağ gözümde meydana...</p>
 </a>
 <time datetime="2020-07-27 00:27:00">27.07.2020</time>
 </article>]

In [44]:
yazilar=[]
basliklar=[]

for link in linkler:
    link1='https://www.karar.com'+link.a.get('href')
    baslik=link.h3.text
    page2=requests.get(link1)
    soup2=soup(page2.content,'html.parser')
    makale=soup2.select('article.article-content')[0].text
    yazilar.append(makale)
    basliklar.append(baslik)

In [45]:
import pandas as pd

In [46]:
df=pd.DataFrame({'Title':basliklar,'Article':yazilar})

In [47]:
df

,Title,Article
0,Engellilerin umudu yapay zeka,\n\nYapay zeka her alanda büyük değişimler ve ...
1,Kuantum yapay zeka,\n\nTeknolojik gelişmeler baş döndürücü hızla ...
2,Astronot 001,\n\nUzay çalışmaları ve uçuşları küçüklüğümden...
3,Çin’in uzay programı tam gaz,\n\nUzay çalışmalarında ne kadar ileride iseni...
4,Yapay zeka ile çip tasarımı,"\n\nGeçtiğimiz hafta Google, bilgisayar çipler..."
5,Venüs’ün iki ziyaretçisi,"\n\nGeçtiğimiz hafta NASA, atmosferini ve jeol..."
6,Yapay zeka ile gerçekçi oyun grafikleri,"\n\nYıllar yıllar önce, daha bilgisayarlarımız..."
7,Yapay zeka iş dünyasını derinden sarsıyor,"\n\nYapay zeka (AI) teknolojisi, tüm iş sektör..."
8,Kariyerinize yapay zekayı ekleyin,\n\nYapay zeka her alanda ciddi ilerlemeler ka...
9,Yapay zeka öğrenmek hiç bu kadar kolay olmamıştı,\n\nSon zamanlarda yapay zeka öğrenmek isteyen...
10,SpaceX bu işi biliyor,\n\nGeçtiğimiz hafta NASA ve SpaceX ilk defa d...
11,Bütün evren bir yapay zekâ algoritması mı?,"\n\nGeçtiğimiz hafta, Microsoft için çalışan f..."
12,Yapay zekâsız dijital dönüşüm,\n\nOn sekiz yıl Los Angeles’ta yaşadıktan son...
13,Çocuklar için yapay zekâ,"\n\nSon 2 yıldır ilköğretim okullarında, lisel..."
14,Yapay zekâyı ne yapmalı?,\n\nSon bir kaç gündür Konya’da iş insanları i...
15,Yapay zekânın yıldızları,\n\nHer alanın kendine göre en iyileri vardır....
16,Geveze yapay zekâ,\n\nİnsanın çok konuşanına geveze deniyor. Pek...
17,Yapay zekânın ürettiği sahte insanlar,\n\nŞikago’lu gazeteci Sydney J. Harris “İnsan...
18,"Eller Mars’a, biz Ay’a",\n\nBu yıl Şubat ayı uzay çalışmaları açısında...
19,Milli Uzay Programı,\n\nGeçtiğimiz hafta en önemli gelişme şüphesi...
20,Yapay zekâ çağında aşk,\n\nYapay zekâ 21. yüzyılın vazgeçilmez bir ar...
21,30 günde yapay zekâ,\n\nHer şey birkaç ay önce aldığım bir email i...
22,Siber güvenlik ve yapay zekâ,"\n\nGünümüzde insanların her attığı adım, yapt..."
23,Trilyon parametreli yapay zekâ,\n\nGeçtiğimiz yaz OpenAI şirketi GPT3 (Genera...
24,Verilerimiz ne kadar güvende?,\n\nFlorida Eyaleti’nin Riviera isimli şehrind...
25,Akıllı makineler ile omuz omuza,"\n\nNesnelerin İnterneti, kısa adıyla IoT, ile..."
26,Ay’da yapay zekâ,\n\nÇin her konuda ABD’de ile kıyasıya bir yar...
27,2021’de yapay zekâ,\n\nBu yıl her açıdan karmaşık ve ilginç bir y...
28,"Süper askerler, biyonik insanlar",\n\nABD istihbarat birimlerinin yayınladığı bi...
29,Çin’in “Yapay Güneş’i”,\n\nÇin Devleti ileri düzey teknolojilerde ABD...
30,2050’de işçi bayramı,\n\nBu yazımızda yapay zekânın sahip olduğu ge...
31,Uzay İstasyonu’nun 20 yılı,"\n\nTam 20 yıl önce, 2 Kasım 2000 tarihinde ik..."
32,Yapay zekânın yalanı,\n\nHiç yalan söylemek zorunda kaldınız mı? Bi...
33,Matematik yerine yapay zekâ,\n\nFacebook sembolik akıl yürütmeyi kullanara...
34,Türkiye Yapay Zekâ Haftası,\n\nGeçtiğimiz hafta Türkiye Yapay Zeka İnisiy...
35,Git gel uzay 6 saat,"\n\nRus Uzay Ajansı Roscosmos, geçtiğimiz 14 E..."
36,Astronomide yapay zekâ uygulamaları,\n\nHayatımda en çok sevdiğim iki alan astrono...
37,NASA’nın 23 milyon dolarlık tuvaleti,\n\nBu yazı bilimsel olmasına rağmen biraz iğr...
38,Yalnızım dostlarım,\n\nKaliforniya Üniversitesi San Diego Tıp Fak...
39,Venüs’ün atmosferinde hayat izleri,"\n\nBir yılı bir gününden kısa, ters, hassas, ..."
40,Uzaktan eğitimle üniversiteler devre dışı,\n\nBirkaç gün önce bende otonom araçlarla ala...
41,Boş zamanınıza talibim,\n\nNewton mekaniğine göre zaman her yerde ayn...
42,Yöneticiler ve iş insanları için yapay zekâ,"\n\nYapay zekâ, makine öğrenmesi ve veri bilim..."
43,Yeniden başlasaydım,\n\nYapay zekâ her geçen gün daha fazla önem k...
44,Humanoidlerle evlenir miydiniz?,\n\nHumanoidleri insan mı yoksa robot mu olduğ...
45,Yapay zekâ bilgisayar programcılığını bitirdi mi?,"\n\nSon birkaç haftadır yapay zekâ dünyası, ya..."
46,Bulut Bilişim ile tanışın,\n\nYıl 1994. İnternet iş modellerinin yeni ye...
47,Beklenen gelecek geldi,\n\nYaklaşık altı aylık bir aradan sonra yenid...

In [107]:
df.shape

(48, 2)

In [109]:
df['Article'][30]

'\n\nBu yazımızda yapay zekânın sahip olduğu geleceğe bir göz atmaya çalışacağız. Yapay zekâ insanların yaptığı rutin işleri ellerinden almaya başladı. Hatta rutin olmayan işlerde bile ciddi mesafeler kaydetti. O sebeple 2050 yılında, artık çalışan insan kalmayacak ve işçi bayramını robotlar kendi kendilerine kutlayacaklar.\xa0Yapay zekâ son zamanlarda her alanda kendisini hissettiriyor. Biz henüz farkında olmasak da kullandığınız akıllı telefonlar, attığınız tweetler, beğendiğiniz resimler, gerçek zamanlı yapay zeka uygulamaları ile analiz ediliyor, davranışlarınız ve siyasi görüşlerinize göre reklam uygulamaları çağrılıp hedefe yönelik reklamlar gösteriliyor. Bir nevi yapay zekâ uygulamaları nabza göre şerbet vererek reklam gelirlerini maksimize ederken, masraf ve israfları aşağı çekiyor. Mesela paylaşımlar ve resimlerden bebeğiniz olup olmadığını anlıyor ve bebek ürünleri reklamını sadece bebeği olan ailelere gösteriyor. Yani yapay zekâ kişilerin ihtiyaçlarını kişisel bazda algılayıp kişisel çözümler üretiyor. \xa0Kullandığınız akıllı telefonlar hakkınızda her gün yüzlerce veri topluyor ve bu veriler bulut bilişim ortamında saklanıyor. Bazen çocuklarınız telefonlarınıza bazı oyunlar yüklüyor ve bu uygulamalar lokasyon, resim, video ve telefon rehberinize erişim istiyor. Erişim vermezseniz oyunu oynayamıyorsunuz, verirseniz bütün bilgileriniz internet ortamına aktarılmış oluyor. Hatta geçtiğimiz hafta 98 milyon Müslümanın namaz vakitlerini öğrenmek, kıble yönünü bulmak ve Kur’an-ı Kerim okumak için telefonuna kurduğu Muslim Pro isimli bir uygulamanın kullanıcı ve onların konum bilgilerini Amerikan askeri birimlerine sattığı ortaya çıktı. Bu uygulama aynı zamanda evde kalmış müslümanlar arasında çöpçatanlık görevi de görüyormuş. Bu bilgiler doğrudan satılmamış fakat arada Babel Street ve X Mode isimli birkaç aracı şirketler tarafından alınıp askeri birimlerle paylaşılmış. Bu aracı şirketler ayrıca eğer bir uygulama yazmışsanız ve bu uygulamayı günlük 50 bin kişi kullanıyorsa, uygulama sahibine konum ve kullanıcı bilgileri karşılığında aylık 1500 dolar katkıda bulunuyormuş. \xa0\nDiyelim ki sosyal medyaya karşısınız ve bir twitter hesabınız yok. Fakat sizin telefon numaranız arkadaşlarınızda mevcut. Arkadaşlarınız bu gibi uygulamalara bağlandığında konum bilgisi, telefon rehberi, resim ve videolara erişim veriyor. Sizin resimleriniz eğer arkadaşınızın telefonunda varsa, algoritmalarımız buradan telefon numaranız ile yüz tanıma sistemleri ile \xa0resimlerden kim olduğunuzu çıkarabiliyor. Sonra aynı telefon numarası başka arkadaşlarınızla karşılaştırılıp sosyal medya hesabınız olmadığı halde varmış gibi hakkınızda veri toplanabiliyor. Hatta bu algoritmalar eğer bir twitter hesabınız olsaydı bugün hangi twitleri atacağınızı %56 doğruluk oranıyla tahmin edebilmektedir. Her attığınız Tweet ile kullanıcı hakkında tam 44 farklı veri toplanmaktadır. Bunu Twitter’dan developer hesabı alıp, veri analizi yapan herkes tarafından çok rahatlıkla görülebilir. \xa0Sosyal medya hesabı olanlar ise zaten ne düşündüklerini ve neler yaşadıklarını her gün paylaşmaktadırlar. Hatta bulundukları konumlardan çok sayıda resim ve video paylaşarak kendileri hakkında herşeyi açıkça ifade etmektedirler. İşte bu veriler gerçek zamanlı (real time) analiz edilmekte ve insanların davranışları, alışkanlıkları, düşünce yapıları, eğitim durumları, siyasi görüşleri ve dini tercihleri hakkında bilgi sahibi olunmaktadır. Hal böyle olunca biz yapay zekâyı henüz bilmiyor bile olsak, tam da içerisinde yaşıyoruz fakat haberimiz yok.\xa0Geçtiğimiz hafta ünlü iş insanı Elon Musk yapay zekânın önümüzdeki beş yıl içerisinde insan zekâsından daha üstün olacağını iddia etti. Musk Dünya’da en fazla yapay zekâ kullanan üç şirket olan Tesla, SpaceX ve Neurolink’in sahibi. Ayrıca geçtiğimiz aylarda en çok konuşulan yapay zekâ uygulaması olan GPT-3’ü geliştiren OpenAI şirketinin de kurucusu. Ancak bazı anlaşmazlıklardan dolayı 2018 yılında bu şirketten ayrıldı. Bu sebeple Musk’ın yapay zeka ile alakalı söyledikleri daha da önem kazanıyor. Ayrıca kendisi yapay zekânın insanlığın sonunu getireceğini iddia ederken, yapay zekâya karşı olmadığını ancak vakit çok geç olmadan önlem alınması gerektiğini belirtiyor.\xa0Yapay zekâ bu hızla ilerlerse, Türkiye olarak bu treni de kaçırmak üzere olduğumuzu söyleyebiliriz. 2050 yıllarını düşündüğümüzde günümüzden çok farklı bir noktada olacağımızı rahatlıkla görüyoruz. Çocuklarını doğum yaparak Dünya’ya getiren son nesil olma ihtimalimiz yüksek. Bilim insanları bebeğin anne karnında şekillenmeye başladıktan sonra bir robota transfer edilebileceğini ve geri kalan gelişimini anne karnına benzeyen bir ortamda, bir robotun karnında tamamlayacağını tahmin ediyorlar. \xa0Film ve eğlence sektörü yapay zekâdan en çok etkilenecek sektörlerden birisi. Artık filmlerde özellik ve güzelliğini sizin belirlediğiniz sanal karakterler oynayacak ve çekilmesini istediğiniz filmi Netflix benzeri bir platforma sipariş vereceksiniz ve o film sadece size özel bir şekilde bir kaç dakika içinde hazır hale gelecek ve istediğiniz platformda izleyebileceksiniz. Sonra bu filmin diğer filmlerle benzerliğinden ve film zevkinizden gişe potansiyelini tahmin edeceksiniz.\xa0Yapay zekâ ile sağlık sektörü çok büyük gelişmelere sahne oluyor. Bu hızla giderse \xa0sağlık hizmetlerini her hastanın genlerine, çevresine ve hayat tarzına göre özelleştirmesine imkan tanıyacak. Yapay zeka, beyin tümörlerinin teşhis edilmesinden bir birey için hangi kanser tedavisinin en iyi sonuç vereceğine karar vermeye kadar kişiselleştirilmiş tıp devrimini yönlendirecek.\xa0Yapay zekâ ile ulaşım araçlarının tamamı otonom olacak. Sarı taksiler ve şoförleri tarihe karışacak. Uçaklar pilotsuz uçacak ve TIRlar sürücü olmadan yollarına devam edecekler. Şu an Arizona Eyaleti’nin birçok şehrinde robotlar yemek dağıtımı yapıyorlar. Ayrıca robot yemek dağıtımına çıktığında sizin konumunuz da değişirse robot da güzergahını değiştiriyor ve sizi bulup yemeğinizi teslim ediyor.\xa0Yapay zekâ eğitim sektörünü de kökünden değiştirecek ve en güzel öğretmenden en güzel ders anlatımını alıp, dersi anlama seviyenize göre dersin dozunu arttırıp azaltacak. Kameralarından duygu analizi yaparak psikolojik durumunuza göre dersi anlayıp anlamadığınıza karar verecek siz anlayana kadar defalarca anlatacak. Hatta beyinler arası bilgi transferi de mümkün olacak.\xa0Her alanda büyük değişimler gerçekleştirecek olan yapay zekâ ile 2050 yılında işçi bayramı sadece robotlar tarafından kutlanacak. Çünkü 2050 yılında artık insanların çalışmasına ihtiyaç kalmayacak.\xa0 \n'