# Tavsiye (Öneri) Sistemleri Film Tavsiyesi

* Bu projede en popüler filmleeri bulup tavsiye etik.

In [22]:
#pip install pandas

In [23]:
import pandas as pd

In [24]:
ratings = pd.read_csv("spark/ml-100k/u.data", sep="\t", header=None, names=["user_id", "movie_id", "rating"], usecols=range(3))

In [25]:
ratings

        user_id  movie_id  rating
0             0        50       5
1             0       172       5
2             0       133       1
3           196       242       3
4           186       302       3
...         ...       ...     ...
99998       880       476       3
99999       716       204       5
100000      276      1090       1
100001       13       225       2
100002       12       203       3

[100003 rows x 3 columns]

In [26]:
movies = pd.read_csv("spark/ml-100k/u.item", sep="|", header=None, encoding="iso-8859-1", usecols=[0, 1], names=["movie_id", "title"])

In [27]:
movies

      movie_id                                      title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [28]:
user = pd.read_csv("spark/ml-100k/u.user", sep="|", header=None, encoding="iso-8859-1", usecols=[0, 1, 2, 3, 4], names=["user_id", "age", "gender", "occupation", "zip_code"])

In [29]:
user

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [30]:
rating = pd.merge(ratings, movies, on="movie_id")
rating

        user_id  movie_id  rating                            title
0             0        50       5                 Star Wars (1977)
1             0       172       5  Empire Strikes Back, The (1980)
2             0       133       1        Gone with the Wind (1939)
3           196       242       3                     Kolya (1996)
4           186       302       3         L.A. Confidential (1997)
...         ...       ...     ...                              ...
99998       880       476       3     First Wives Club, The (1996)
99999       716       204       5        Back to the Future (1985)
100000      276      1090       1                    Sliver (1993)
100001       13       225       2            101 Dalmatians (1996)
100002       12       203       3                Unforgiven (1992)

[100003 rows x 4 columns]

In [31]:
#rating = pd.merge(rating, user, on="user_id")

In [32]:
#rating

In [36]:
rating.title.value_counts()

title
Star Wars (1977)                                      584
Contact (1997)                                        509
Fargo (1996)                                          508
Return of the Jedi (1983)                             507
Liar Liar (1997)                                      485
                                                     ...
Mamma Roma (1962)                                       1
Eighth Day, The (1996)                                  1
Girls Town (1996)                                       1
Silence of the Palace, The (Saimt el Qusur) (1994)      1
Dadetown (1995)                                         1
Name: count, Length: 1664, dtype: int64

In [37]:
import numpy as np

In [50]:
movie_rating = rating.groupby("title").agg({"rating": [np.size, np.sum, np.mean ]})

In [51]:
movie_rating

                                      rating
                                        size  sum      mean
title
'Til There Was You (1997)                  9   21  2.333333
1-900 (1994)                               5   13  2.600000
101 Dalmatians (1996)                    109  317  2.908257
12 Angry Men (1957)                      125  543  4.344000
187 (1997)                                41  124  3.024390
...                                      ...  ...       ...
Young Guns II (1990)                      44  122  2.772727
Young Poisoner's Handbook, The (1995)     41  137  3.341463
Zeus and Roxanne (1997)                    6   13  2.166667
unknown                                    9   31  3.444444
Á köldum klaka (Cold Fever) (1994)         1    3  3.000000

[1664 rows x 3 columns]

In [52]:
en_cok_rating_sirasi = movie_rating.sort_values(by=[("rating", "mean")], ascending=False)

In [53]:
en_cok_rating_sirasi

                                                  rating
                                                    size sum mean
title
Aiqing wansui (1994)                                   1   5  5.0
Entertaining Angels: The Dorothy Day Story (1996)      1   5  5.0
Santa with Muscles (1996)                              2  10  5.0
Prefontaine (1997)                                     3  15  5.0
They Made Me a Criminal (1939)                         1   5  5.0
...                                                  ...  ..  ...
Pharaoh's Army (1995)                                  1   1  1.0
August (1996)                                          1   1  1.0
Babyfever (1994)                                       2   2  1.0
Amityville: A New Generation (1993)                    5   5  1.0
Woman in Question, The (1950)                          1   1  1.0

[1664 rows x 3 columns]

In [60]:
toplam_sum_sirasi = en_cok_rating_sirasi.sort_values(by=[("rating", "sum")], ascending=False)

In [61]:
toplam_sum_sirasi

                                rating
                                  size   sum      mean
title
Star Wars (1977)                   584  2546  4.359589
Fargo (1996)                       508  2111  4.155512
Return of the Jedi (1983)          507  2032  4.007890
Contact (1997)                     509  1936  3.803536
Raiders of the Lost Ark (1981)     420  1786  4.252381
...                                ...   ...       ...
Butterfly Kiss (1995)                1     1  1.000000
Mille bolle blu (1993)               1     1  1.000000
Modern Affair, A (1995)              1     1  1.000000
Mostro, Il (1994)                    1     1  1.000000
Man from Down Under, The (1943)      1     1  1.000000

[1664 rows x 3 columns]

In [62]:
toplam_rating_sum = toplam_sum_sirasi["rating"]["sum"].sum()

In [63]:
toplam_rating_sum

np.int64(352997)

In [64]:
toplam_sum_sirasi["rating"]["sum"]

title
Star Wars (1977)                   2546
Fargo (1996)                       2111
Return of the Jedi (1983)          2032
Contact (1997)                     1936
Raiders of the Lost Ark (1981)     1786
                                   ...
Butterfly Kiss (1995)                 1
Mille bolle blu (1993)                1
Modern Affair, A (1995)               1
Mostro, Il (1994)                     1
Man from Down Under, The (1943)       1
Name: sum, Length: 1664, dtype: int64

In [65]:
toplam_sum_sirasi["percentage"] = toplam_sum_sirasi["rating"]["sum"].div(toplam_rating_sum) * 100

In [66]:
toplam_sum_sirasi["rank"] = toplam_sum_sirasi["percentage"].rank(ascending=False)

In [67]:
toplam_sum_sirasi

                                rating                 percentage    rank
                                  size   sum      mean
title
Star Wars (1977)                   584  2546  4.359589   0.721253     1.0
Fargo (1996)                       508  2111  4.155512   0.598022     2.0
Return of the Jedi (1983)          507  2032  4.007890   0.575642     3.0
Contact (1997)                     509  1936  3.803536   0.548447     4.0
Raiders of the Lost Ark (1981)     420  1786  4.252381   0.505953     5.0
...                                ...   ...       ...        ...     ...
Butterfly Kiss (1995)                1     1  1.000000   0.000283  1636.0
Mille bolle blu (1993)               1     1  1.000000   0.000283  1636.0
Modern Affair, A (1995)              1     1  1.000000   0.000283  1636.0
Mostro, Il (1994)                    1     1  1.000000   0.000283  1636.0
Man from Down Under, The (1943)      1     1  1.000000   0.000283  1636.0

[1664 rows x 5 columns]