# Matrix Factorization Tavsiye (Öneri) Sistemleri Film Tavsiyesi

* Bu projede en popüler filmleeri bulup tavsiye etik.

In [1]:
#pip install pandas

In [2]:
import pandas as pd

In [3]:
ratings = pd.read_csv("spark/ml-100k/u.data", sep="\t", header=None, names=["user_id", "movie_id", "rating"], usecols=range(3))

In [4]:
ratings

        user_id  movie_id  rating
0             0        50       5
1             0       172       5
2             0       133       1
3           196       242       3
4           186       302       3
...         ...       ...     ...
99998       880       476       3
99999       716       204       5
100000      276      1090       1
100001       13       225       2
100002       12       203       3

[100003 rows x 3 columns]

In [5]:
movies = pd.read_csv("spark/ml-100k/u.item", sep="|", header=None, encoding="iso-8859-1", usecols=[0, 1], names=["movie_id", "title"])

In [6]:
movies

      movie_id                                      title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [7]:
user = pd.read_csv("spark/ml-100k/u.user", sep="|", header=None, encoding="iso-8859-1", usecols=[0, 1, 2, 3, 4], names=["user_id", "age", "gender", "occupation", "zip_code"])

In [8]:
user

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [9]:
rating = pd.merge(ratings, movies, on="movie_id")
rating

        user_id  movie_id  rating                            title
0             0        50       5                 Star Wars (1977)
1             0       172       5  Empire Strikes Back, The (1980)
2             0       133       1        Gone with the Wind (1939)
3           196       242       3                     Kolya (1996)
4           186       302       3         L.A. Confidential (1997)
...         ...       ...     ...                              ...
99998       880       476       3     First Wives Club, The (1996)
99999       716       204       5        Back to the Future (1985)
100000      276      1090       1                    Sliver (1993)
100001       13       225       2            101 Dalmatians (1996)
100002       12       203       3                Unforgiven (1992)

[100003 rows x 4 columns]

In [10]:
#rating = pd.merge(rating, user, on="user_id")

In [11]:
#rating

In [12]:
rating.title.value_counts()

title
Star Wars (1977)                                      584
Contact (1997)                                        509
Fargo (1996)                                          508
Return of the Jedi (1983)                             507
Liar Liar (1997)                                      485
                                                     ...
Mamma Roma (1962)                                       1
Eighth Day, The (1996)                                  1
Girls Town (1996)                                       1
Silence of the Palace, The (Saimt el Qusur) (1994)      1
Dadetown (1995)                                         1
Name: count, Length: 1664, dtype: int64

In [28]:
matrix_func = rating.pivot_table(index=["user_id"], columns=["title"],values="rating")

In [29]:
matrix_func

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN

In [30]:
matrix_func["Star Wars (1977)"]

user_id
0      5.0
1      5.0
2      5.0
3      NaN
4      5.0
      ...
939    NaN
940    4.0
941    NaN
942    5.0
943    4.0
Name: Star Wars (1977), Length: 944, dtype: float64

In [31]:
Star_W_R = matrix_func["Star Wars (1977)"]

In [32]:
Star_W_R.value_counts()

Star Wars (1977)
5.0    326
4.0    176
3.0     57
2.0     16
1.0      9
Name: count, dtype: int64

In [33]:
matrix_func[["Star Wars (1977)", "101 Dalmatians (1996)"]].corr()

title                  Star Wars (1977)  101 Dalmatians (1996)
title
Star Wars (1977)               1.000000               0.211132
101 Dalmatians (1996)          0.211132               1.000000

In [34]:
sm = matrix_func.corrwith(Star_W_R)

/home/zaid/Desktop/Yapay-Zeka-Kursu/venv/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/zaid/Desktop/Yapay-Zeka-Kursu/venv/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/zaid/Desktop/Yapay-Zeka-Kursu/venv/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:3015: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/home/zaid/Desktop/Yapay-Zeka-Kursu/venv/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:2888: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/home/zaid/Desktop/Yapay-Zeka-Kursu/venv/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

In [35]:
sm.sort_values(ascending=False)

title
Star Wars (1977)                           1.0
Stripes (1981)                             1.0
Hollow Reed (1996)                         1.0
Man of the Year (1995)                     1.0
Cosi (1996)                                1.0
                                          ...
Wonderland (1997)                          NaN
Wooden Man's Bride, The (Wu Kui) (1994)    NaN
Yankee Zulu (1994)                         NaN
You So Crazy (1994)                        NaN
Á köldum klaka (Cold Fever) (1994)         NaN
Length: 1664, dtype: float64

In [36]:
import numpy as np

In [37]:
Matrix_stats = rating.groupby("title").agg({"rating" : [np.size, np.mean]})

In [38]:
Matrix_stats.head()

                          rating
                            size      mean
title
'Til There Was You (1997)      9  2.333333
1-900 (1994)                   5  2.600000
101 Dalmatians (1996)        109  2.908257
12 Angry Men (1957)          125  4.344000
187 (1997)                    41  3.024390

In [39]:
pm = Matrix_stats[Matrix_stats["rating"]["size"] > 100]

In [40]:
smdata = pd.DataFrame(sm, columns=["similarity"])

In [41]:
pm.columns = pm.columns.get_level_values(0)
df = pm.join(smdata)

In [42]:
df.sort_values(["similarity"], ascending= False)

,rating,rating,similarity
title,,,
Star Wars (1977),584,4.359589,1.000000
"Empire Strikes Back, The (1980)",368,4.206522,0.748353
Return of the Jedi (1983),507,4.007890,0.672556
Raiders of the Lost Ark (1981),420,4.252381,0.536117
Austin Powers: International Man of Mystery (1997),130,3.246154,0.377433
...,...,...,...
"Edge, The (1997)",113,3.539823,-0.127167
As Good As It Gets (1997),112,4.196429,-0.130466
Crash (1996),128,2.546875,-0.148507
G.I. Jane (1997),175,3.360000,-0.176734
"First Wives Club, The (1996)",160,3.018750,-0.194496