# Data Analysis with Pandas - Problem Set


#### Reading in Data

1. Read in the comma-separated file "client_list.csv". Assign as variable `df1`.
2. Read in the delimted file "client_list.table". Assign as variable as `df2`.
3. Read in the fixed-width file "client_list.txt". Assign as variable `df3`
4. Read in the comma-separated file "client_list.csv", skip the first 3 rows, and ignore the header. Do not assign to variable (just return a view).
5. Read in the comma-separated file "client_list.csv". Set the column headers in all caps. Assign as variable `df`.
6. Read in the comma-separated file "client_list_practice.csv" and only extract the columns ["FIRST_NAME","AGE","EYE_COLOR"]. Do not assign to a variable.

In [ ]:
import pandas as pd

df1 = pd.read_csv('client_list.csv')
df1.head()

In [78]:
#df2 = pd.read_table('client_list.table')
df2 = pd.read_csv('client_list.table', sep=';')
df2.head()

  first_name LAST_NAME gender  Age Hair_COLOR eye_Color
0   Jennifer     Jones      F   27      black     brown
1      Jaime   Roberts      M   32      brown     hazel
2    Michael   Johnson      M   55        red     green
3       Mary     Adams      F   42     blonde      blue
4     Robert  Phillips      M   37     blonde     brown

In [79]:
df3 = pd.read_fwf('client_list.txt')
df3.head()

  first_name LAST_NAME gender  Age Hair_COLOR eye_Color
0   Jennifer     Jones      F   27      black     brown
1      Jaime   Roberts      M   32      brown     hazel
2    Michael   Johnson      M   55        red     green
3       Mary     Adams      F   42     blonde      blue
4     Robert  Phillips      M   37     blonde     brown

In [ ]:
pd.read_csv("client_list.csv", skiprows=3, header=None).head()

In [81]:
df = pd.read_csv('client_list.csv')
#df.columns = df.columns.str.upper()
df.columns = [x.upper() for x in df.columns]
df.head()

  FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
0   Jennifer     Jones      F   27      black     brown
1      Jaime   Roberts      M   32      brown     hazel
2    Michael   Johnson      M   55        red     green
3       Mary     Adams      F   42     blonde      blue
4     Robert  Phillips      M   37     blonde     brown

In [ ]:
pd.read_csv('client_list_practice.csv', usecols=["FIRST_NAME","AGE","EYE_COLOR"]).head()

#### Slicing a Data Set

7. Slice rows 5 through 11 of `df`. Can you provide two ways of doing this?
8. Return only the columns ['LAST_NAME','AGE','HAIR_COLOR'] for `df`. Can you provide two ways of doing this?
9. Combine problems 1 and 2: return rows 5 though 11 and columns  ['LAST_NAME','AGE','HAIR_COLOR'] for `df`. Can you provide two ways of doing this?

In [16]:
# 1.way of sclicing
df_sclice_1 = df.iloc[5:12]
df_sclice_1

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel
11    Jessica    Rabbit      F   19      black      blue

In [29]:
#2.way of sclicing
df_sclice_2 = df[5:12]
df_sclice_2

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel
11    Jessica    Rabbit      F   19      black      blue

In [30]:
#3.way of sclicing
df_sclice_3 = df.loc[5:11]
def_sclice_3

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel
11    Jessica    Rabbit      F   19      black      blue

In [32]:
#1. way of selecting columns of df
df[['LAST_NAME','AGE','HAIR_COLOR']].head()

  LAST_NAME  AGE HAIR_COLOR
0     Jones   27      black
1   Roberts   32      brown
2   Johnson   55        red
3     Adams   42     blonde
4  Phillips   37     blonde

In [35]:
#2. way of selecting columns of df
df.loc[ : ,['LAST_NAME','AGE','HAIR_COLOR']].head()

  LAST_NAME  AGE HAIR_COLOR
0     Jones   27      black
1   Roberts   32      brown
2   Johnson   55        red
3     Adams   42     blonde
4  Phillips   37     blonde

In [44]:
# 1.way of Combine problems 1 and 2:
df[['LAST_NAME', 'AGE', 'HAIR_COLOR']][5:12]

   LAST_NAME  AGE HAIR_COLOR
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black
11    Rabbit   19      black

In [37]:
# 2.way of Combine problems 1 and 2:
df.loc[ 5:11 ,['LAST_NAME','AGE','HAIR_COLOR']]

   LAST_NAME  AGE HAIR_COLOR
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black
11    Rabbit   19      black

#### Simple Queries

10. Find the subset of `df` where the client's last name is "Smith".
11. Find the subset of `df` where the client's hair color is not black.
12. Find the subset of `df` where the client's hair color is red and reset the values to "ginger".

In [47]:
df[df['LAST_NAME'] == 'Smith']

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel

In [48]:
df[df['HAIR_COLOR'] != 'black']

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
1       Jaime   Roberts      M   32      brown     hazel
2     Michael   Johnson      M   55        red     green
3        Mary     Adams      F   42     blonde      blue
4      Robert  Phillips      M   37     blonde     brown
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
12      Molly    Bryant      F   21      brown      blue
13      Jaime  Anderson      F   46      brown     green

In [59]:
#df[df['HAIR_COLOR'] == 'red'].fillna('ginger') bu dogru degil cunku fillna sadece NaN degerlerini degistirir.
#df.loc[df['HAIR_COLOR'] == 'red', 'HAIR_COLOR'] = 'ginger'
df['HAIR_COLOR'] = df['HAIR_COLOR'].replace('red', 'ginger')
df[df['HAIR_COLOR'] == 'ginger']

  FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
2    Michael   Johnson      M   55     ginger     green

#### Complex Queries

13. Find the subset of `df` where the clients are females older than 30 years.
14. Repeat problem 1, but return only the hair color and eye color.
15. Find the unique combination of hair and eye color for women older than 25 years.

In [69]:
df[(df['AGE'] > 30) & (df['GENDER'] == 'F')]

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
3        Mary     Adams      F   42     blonde      blue
9    Jennifer     Smith      F   36      black     brown
13      Jaime  Anderson      F   46      brown     green

In [82]:
#df_30_ustu_f = df[(df['AGE'] > 30) & (df['GENDER'] == 'F')]
#df_30_ustu_f[['HAIR_COLOR', 'EYE_COLOR']]
df[(df['AGE'] > 30) & (df['GENDER'] == 'F')][['HAIR_COLOR', 'EYE_COLOR']]

   HAIR_COLOR EYE_COLOR
3      blonde      blue
9       black     brown
13      brown     green

In [83]:
df[(df['AGE'] > 25) & (df['GENDER'] == 'F')][['HAIR_COLOR', 'EYE_COLOR']].drop_duplicates()

   HAIR_COLOR EYE_COLOR
0       black     brown
3      blonde      blue
13      brown     green


#### Additional Dataframe Operations

16. Perform a `merge` using "client_list.csv" and "customer_id_list.csv". Assign the resulting dataframe as `clients`.
17. Perform a `merge` using `clients` and "purchase_log.csv" and limit the subset to only clients who made purchases. Assign the resulting dataframe as `detailed_sales`.
18. Use `groupby` to find the client who spent the most money on purchases. Determine how much he/she spent. HINT: save the intermediate dataframe from using `groupby` as `spenders` before applying slicing to determine the client who spent the most money on purchases.
19. (BONUS) Modify the answer to problem 3 slightly to determine exactly what items where purchased by the top spending client.

In [95]:
df = pd.read_csv('client_list.csv')
df.columns = [x.upper() for x in df.columns]
df2 = pd.read_csv('customer_id_list.csv')
client = pd.merge(left=df, right=df2, how='left', on=['LAST_NAME','FIRST_NAME','GENDER','AGE'])
client.head()

  FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR  CUSTOMER_ID
0   Jennifer     Jones      F   27      black     brown            1
1      Jaime   Roberts      M   32      brown     hazel            2
2    Michael   Johnson      M   55        red     green            3
3       Mary     Adams      F   42     blonde      blue            4
4     Robert  Phillips      M   37     blonde     brown            5

In [96]:
purchase_log = pd.read_csv('purchase_log.csv')
datailed_sale = pd.merge(left=client, right=purchase_log, how='inner', on='CUSTOMER_ID')
datailed_sale.head()

,FIRST_NAME,LAST_NAME,GENDER,AGE,HAIR_COLOR,EYE_COLOR,CUSTOMER_ID,DATE,SKU,ITEM_DESCRIPTION,PRICE
0,Jennifer,Jones,F,27,black,brown,1,01/01/2015,39490,aspirin,12.99
1,Jaime,Roberts,M,32,brown,hazel,2,12/24/2014,39933,gift card,50.00
2,Mary,Adams,F,42,blonde,blue,4,10/31/2014,94586,Superman costume,39.99
3,Thomas,Moore,M,60,brown,blue,6,09/13/2014,22495,birthday card,3.99
4,Michael,Smith,M,58,brown,brown,9,02/14/2015,23493,box of chocolates,29.99

In [120]:
spenders = datailed_sale.groupby(['FIRST_NAME','LAST_NAME','CUSTOMER_ID'])['PRICE'].sum().reset_index()
spenders = spenders.sort_values(by='PRICE', ascending=False)
top_spender = spenders.iloc[0]
top_spender

#spenders = datailed_sale.groupby(['CUSTOMER_ID','FIRST_NAME','LAST_NAME','GENDER','AGE'], as_index=False)['PRICE'].sum()
#top_spender = spenders[spenders.PRICE==spenders.PRICE.max()]
#top_spender

   CUSTOMER_ID FIRST_NAME LAST_NAME GENDER  AGE   PRICE
4            9    Michael     Smith      M   58  229.98

In [131]:
top_spender_id = top_spender.reset_index(drop=True).loc[0,'CUSTOMER_ID']
top_spender_items = datailed_sale[datailed_sale['CUSTOMER_ID'] == top_spender_id][['ITEM_DESCRIPTION','PRICE']]
top_spender_items

      ITEM_DESCRIPTION   PRICE
4    box of chocolates   29.99
5  bottle of champagne  199.99

#### Writing Files

20. Save `detailed_sales` as a csv file named "df_out.csv" with no indices.
21. Save `detailed_sales` to a pickle file named "df_out.p"

In [132]:
datailed_sale.to_csv("df_out.csv", index=False)

In [133]:
datailed_sale.to_pickle("df_out.p")